import { getGallery, heroFromPool } from './gallery-pools.mjs';

function P(x) {
  const pool = x.pool || 'concert';
  const gallery = x.gallery || getGallery(pool);
  const hero = x.hero || heroFromPool(pool);
  return {
    ...x,
    hero,
    gallery,
    thumb: x.thumb || hero,
  };
}

export const PROJECTS = [
  P({
    file: 'dem-hoi-chao-tan-sinh-vien-k69.html',
    pool: 'concert',
    titlePlain: 'Đêm hội chào tân sinh viên K69 — Học viện Nông nghiệp | FT GROUP E&E',
    descPlain:
      'Đại nhạc hội chào K69 tại Học viện Nông nghiệp Việt Nam: Tiên Tiên, Thanh Hưng; sân khấu âm thanh ánh sáng chuyên nghiệp.',
    keywords: 'chào tân sinh viên, đại nhạc hội, Học viện Nông nghiệp, FT GROUP E&E, sự kiện Hà Nội',
    filters: ['dai-nhac-hoi', 'chao-tan-sinh-vien'],
    cardTitle: 'Đêm hội chào TSV K69',
    cardCat: 'Đại nhạc hội · Chào tân sinh viên',
    cardDesc: 'Tiên Tiên & Thanh Hưng — không khí bùng nổ, sân khấu chuẩn concert.',
    cat: 'Đại nhạc hội / Chào tân sinh viên',
    loc: 'Học viện Nông nghiệp Việt Nam',
    h1: 'Đêm hội chào tân sinh viên K69',
    overview: {
      name: 'Đêm hội chào tân sinh viên K69',
      client: 'Học viện Nông nghiệp Việt Nam',
      place: 'Học viện Nông nghiệp Việt Nam (Trâu Quỳ, Gia Lâm, Hà Nội)',
      time: 'Theo lịch Đoàn — Hội sinh viên',
      scale: 'Đại nhạc hội sân trường — quy mô lớn',
      services: 'Sân khấu, line array, beam, LED, MC/DJ, điều phối, kỹ thuật âm thanh ánh sáng',
    },
    intros: [
      { h: 'Mục tiêu chương trình', p: 'Chào khóa mới với không khí trẻ, sôi động — kết nối tân sinh viên với đời sống Đoàn, Hội và nhà trường.' },
      { h: 'Nội dung nổi bật', p: 'Ca sĩ khách mời: Tiên Tiên và Thanh Hưng; dàn dựng âm thanh ánh sáng professional để đảm bảo trải nghiệm concert.' },
      { h: 'Phía FT GROUP E&E', p: 'Thiết kế sân khấu, timing, backup máy phát — vận hành liên tục suốt đêm nhạc.' },
    ],
    quote: 'Khán đài hót theo từng bài — âm thanh rõ, dàn đèn đúng nhịp show.',
    cite: 'Phản hồi BTC sinh viên',
    results: [
      'Sân khấu vận hành ổn định suốt đêm',
      'Không gián trẻ trung, check-in & cổng chào gọn gàng',
      'Đồng bộ MC và tiết mục khách mời',
    ],
    experienceBullets: [
      'Sinh viên tập trung đông, không khí cuồng nhiệt như festival.',
      'Dàn light chase theo beat — cảm giác concert thực thụ.',
    ],
    experienceQuote: 'Đêm như một show lớn ngay tại sân trường.',
    feedback: 'BTC đánh giá cao phần kỹ thuật âm thanh và phối hợp với nghệ sĩ.',
    related: ['dem-hoi-chao-tan-sinh-vien-k70.html', 'dai-nhac-hoi-chao-tan-sinh-vien-cdltk.html', 'dem-hoi-chao-tan-sinh-vien-khoa-du-lich.html'],
  }),

  P({
    file: 'dem-hoi-chao-tan-sinh-vien-khoa-du-lich.html',
    pool: 'concert',
    titlePlain: 'Đêm hội chào tân sinh viên Khoa Du lịch — HVNN Việt Nam | FT GROUP E&E',
    descPlain: 'Chương trình chào tân Khoa Du lịch; Học viện Nông nghiệp Việt Nam. Tổ chức FT GROUP E&E.',
    keywords: 'chào tân sinh viên, Khoa Du lịch, HVNN, FT GROUP E&E',
    filters: ['chao-tan-sinh-vien'],
    cardTitle: 'Chào TSV Khoa Du lịch',
    cardCat: 'Chào tân sinh viên',
    cardDesc: 'Gắn kết tân sinh viên Khoa Du lịch — bản sắc trẻ, sân khấu gọn.',
    cat: 'Chào tân sinh viên',
    loc: 'Học viện Nông nghiệp Việt Nam',
    h1: 'Đêm hội chào tân sinh viên Khoa Du lịch',
    overview: {
      name: 'Đêm hội Khoa Du lịch',
      client: 'Khoa Du lịch — HVNN Việt Nam',
      place: 'Học viện Nông nghiệp Việt Nam',
      time: 'Theo lịch khoa',
      scale: 'Sự kiện sân trường',
      services: 'Sân khấu, âm thanh, ánh sáng, MC',
    },
    intros: [
      { h: 'Ý tưởng', p: 'Không gian gần gũi, nhấn mạnh ngành Du lịch với backdrop và phần mở màn tương tác.' },
      { h: 'Triển khai', p: 'Dàn âm line array vừa phủ sân, đèn wash ấm cho buổi tối ngoài trời/ hội trường.' },
      { h: 'Kết quả', p: 'Tân sinh viên tham gia game, giao lưu ổn định trong khung giờ.' },
    ],
    quote: 'Chương trình đúng tinh thần khoa, MC và âm thanh ổn.',
    cite: 'Đại diện khoa',
    results: ['Đúng tiến độ', 'Không cố điện', 'Phản hồi tích cực từ tân K'],
    experienceBullets: ['Khán giả gần sân khấu', 'Không khí đoàn kết khoa'],
    feedback: 'Khoa đồng hành suốt buổi, sinh viên vui và gắn kết.',
    related: ['dem-hoi-chao-tan-sinh-vien-khoa-kinh-te.html', 'dem-hoi-chao-tan-sinh-vien-k69.html', 'le-ky-niem-ngay-nha-giao-viet-nam.html'],
  }),

  P({
    file: 'dem-hoi-chao-tan-sinh-vien-khoa-kinh-te.html',
    pool: 'concert',
    titlePlain: 'Đêm hội chào tân sinh viên Khoa Kinh tế — HVNN | FT GROUP E&E',
    descPlain: 'Chào tân Khoa Kinh tế tại Học viện Nông nghiệp Việt Nam — FT GROUP E&E tổ chức sân khấu & âm thanh.',
    keywords: 'chào tân sinh viên, Khoa Kinh tế, HVNN, FT GROUP E&E',
    filters: ['chao-tan-sinh-vien'],
    cardTitle: 'Chào TSV Khoa Kinh tế',
    cardCat: 'Chào tân sinh viên',
    cardDesc: 'Đêm hội tại HVNN — sân khấu và ánh sáng đồng bộ.',
    cat: 'Chào tân sinh viên',
    loc: 'Học viện Nông nghiệp Việt Nam',
    h1: 'Đêm hội chào tân sinh viên Khoa Kinh tế',
    overview: {
      name: 'Đêm hội Khoa Kinh tế',
      client: 'Khoa Kinh tế — HVNN Việt Nam',
      place: 'Học viện Nông nghiệp Việt Nam',
      time: 'Theo lịch khoa',
      scale: 'Sự kiện sân trường',
      services: 'Sân khấu, âm thanh, ánh sáng, vận hành',
    },
    intros: [
      { h: 'Mục tiêu', p: 'Chào mừng tân sinh viên khối Kinh tế với không khí trẻ trung.' },
      { h: 'Giải pháp', p: 'Bố cục sân khấu rõ luồng di chuyển; thiết kế ánh sáng phù hợp buổi tối.' },
      { h: 'Tổng kết', p: 'Chương trình đồng bộ MC, game ngắn, tiết mục văn nghệ.' },
    ],
    quote: 'Chương trình gọn, đúng giờ và vui.',
    cite: 'Ban cán sự lớp',
    results: ['Vận hành suôn sẻ', 'Sinh viên tham gia đông', 'Kỹ thuật ổn định'],
    experienceBullets: ['Không gian khoa riêng, dễ tương tác'],
    feedback: 'Phối hợp tốt với đại diện khoa và Đoàn.',
    related: ['dem-hoi-chao-tan-sinh-vien-khoa-du-lich.html', 'dem-hoi-chao-tan-sinh-vien-k69.html', 'ngay-hoi-chung-toi-la-chien-si.html'],
  }),

  P({
    file: 'dem-hoi-happy-christmas.html',
    pool: 'christmas',
    titlePlain: 'Đêm hội Happy Christmas — Cao đẳng Du lịch và Thương mại Hà Nội | FT GROUP E&E',
    descPlain: 'Sự kiện Noel học đường — trang trí đỏ xanh, ánh sáng festive, không khí Giáng sinh.',
    keywords: 'Noel trường học, Christmas event, Cao đẳng Du lịch Thương mại Hà Nội, FT GROUP E&E',
    filters: ['su-kien-truong-hoc'],
    cardTitle: 'Đêm hội Happy Christmas',
    cardCat: 'Sự kiện trường học · Noel',
    cardDesc: 'Không khí lễ hội đỏ—xanh, đèn và decor cinematic.',
    cat: 'Sự kiện trường học / Noel',
    loc: 'Trường Cao đẳng Du lịch và Thương mại Hà Nội',
    h1: 'Đêm hội “Happy Christmas”',
    overview: {
      name: 'Happy Christmas',
      client: 'Trường Cao đẳng Du lịch và Thương mại Hà Nội',
      place: 'Cơ sở trường (theo kế hoạch BTC)',
      time: 'Mùa Giáng sinh',
      scale: 'Đêm hội học đường',
      services: 'Trang trí theme Noel, ánh sáng, sân khấu, âm thanh',
    },
    intros: [
      { h: 'Không khí', p: 'Tô điểm đỏ — xanh, đèn LED và decor để không gian ấm và lễ hội.' },
      { h: 'Chiếu sáng', p: 'Wash và đèn phụ trợ chụp ảnh — phù hợp backdrop check-in.' },
      { h: 'Vận hành', p: 'Rundown MC, nhạc nền, hiệu ứng nhẹ đúng khung giờ trường.' },
    ],
    quote: 'Không khí Noel rõ nét — sinh viên check-in liên tục.',
    cite: 'BTC trường',
    results: ['Decor ánh sáng đồng bộ', 'Không gian ảnh đẹp', 'An toàn điện'],
    experienceBullets: ['Backdrop chụp hình đông đảo', 'Nhạc và đèn đúng mood Giáng sinh'],
    feedback: 'Trường hài lòng phần trang trí và timeline.',
    related: ['dai-nhac-hoi-chao-tan-sinh-vien-cdltk.html', 'ngay-hoi-le-hoi-nuoc.html', 'dem-hoi-chao-tan-sinh-vien-k69.html'],
  }),

  P({
    file: 'dem-nhac-gieo-yeu-thuong.html',
    pool: 'charity',
    titlePlain: 'Đêm nhạc Gieo yêu thương — thiện nguyện | FT GROUP E&E',
    descPlain: 'Đêm nhạc thiện nguyện — hơn 1000 khách; EDISO Ecopark; đấu giá tranh; góp xây điểm trường Lai Châu.',
    keywords: 'đêm nhạc thiện nguyện, Ecopark, FT GROUP E&E, từ thiện',
    filters: ['dai-nhac-hoi', 'su-kien-truong-hoc'],
    cardTitle: 'Đêm nhạc Gieo yêu thương',
    cardCat: 'Đại nhạc hội · Thiện nguyện',
    cardDesc: '1000+ khách — đấu giá tranh, cảm xúc và sân khấu ý nghĩa.',
    cat: 'Đại nhạc hội / Thiện nguyện',
    loc: 'Trường EDISO Ecopark',
    h1: 'Đêm nhạc “Gieo yêu thương”',
    overview: {
      name: 'Gieo yêu thương',
      client: 'Trường EDISO Ecopark & đối tác BTC',
      place: 'Trường EDISO Ecopark',
      time: 'Theo mùa sự kiện',
      scale: 'Hơn 1000 khách tham dự',
      services: 'Sân khấu lớn, âm thanh, beam, vận hành đêm nhạc, media',
    },
    intros: [
      { h: 'Tầm nhìn', p: 'Lan tỏa yêu thương qua âm nhạc — đấu giá tranh từ thiện, xây điểm trường Lao Lử Đề, Lai Châu.' },
      { h: 'Kỹ thuật', p: 'Sân khấu đủ sức chứa đám đông; âm thanh phủ đều khán đài.' },
      { h: 'Cảm xúc', p: 'Thiết kế ánh sáng ấm, nhấn khoảnh khắc tri ân và phần đấu giá.' },
    ],
    quote: 'Đêm nhạc chạm đến cảm xúc — MC và ánh sáng đồng hành cùng thông điệp.',
    cite: 'Đại diện BTC',
    results: ['1000+ lượt tham dự', 'Ấn tượng sân khấu', 'Thông điệp nhân văn rõ'],
    experienceBullets: ['Khán đài đồng thanh ca', 'Không khí xúc động khi đấu giá'],
    experienceQuote: 'Lan tỏa được từ sân khấu đến khán phòng.',
    feedback: 'Đối tác đánh giá cao phần vận hành êm, an toàn.',
    related: ['dai-nhac-hoi-chao-tan-sinh-vien-cdltk.html', 'dem-hoi-chao-tan-sinh-vien-k69.html', 'le-ky-niem-ngay-nha-giao-viet-nam.html'],
  }),

  P({
    file: 'dai-nhac-hoi-chao-tan-sinh-vien-cdltk.html',
    pool: 'concert',
    titlePlain: 'Đại nhạc hội chào tân sinh viên — CDLTK Hà Nội | FT GROUP E&E',
    descPlain: 'Đại nhạc hội tại Trường Cao đẳng Du lịch và Thương mại Hà Nội. Khách mời: Anh Thơ, Quân AP.',
    keywords: 'đại nhạc hội, Anh Thơ, Quân AP, Cao đẳng Du lịch Thương mại, FT GROUP E&E',
    filters: ['dai-nhac-hoi'],
    cardTitle: 'Đại nhạc hội chào TSV',
    cardCat: 'Đại nhạc hội',
    cardDesc: 'Anh Thơ & Quân AP — đêm nhạc bùng nổ tại CDLTK.',
    cat: 'Đại nhạc hội',
    loc: 'Trường Cao đẳng Du lịch và Thương mại Hà Nội',
    h1: 'Đại nhạc hội chào tân sinh viên',
    overview: {
      name: 'Đại nhạc hội chào TSV',
      client: 'Trường CDLTK Hà Nội',
      place: 'Trường Cao đẳng Du lịch và Thương mại Hà Nội',
      time: 'Theo lịch nhà trường',
      scale: 'Đại nhạc hội ngoài trời / sân',
      services: 'Sân khấu, line array, beam, crew kỹ thuật, điều phối nghệ sĩ',
    },
    intros: [
      { h: 'Line-up', p: 'Khách mời: Anh Thơ, Quân AP — kết hợp dòng nhạc đa thế hệ.' },
      { h: 'Sân khấu', p: 'Thiết kế dàn đèn beam, wash và haze có kiểm soát cho góc quay và ảnh.' },
      { h: 'Kỹ thuật', p: 'Monitor nghệ sĩ, backup máy phát, checklist an toàn lưới điện.' },
    ],
    quote: 'Khán giả đứng lên theo từng bài hit — chất show cao.',
    cite: 'Đại diện BTC trường',
    results: ['Show chạy đúng rundown', 'Chất lượng âm hình ổn', 'Nghệ sĩ hài lòng monitor'],
    experienceBullets: ['Fan cồng vỗ tay theo nhịp', 'Ánh sáng biến hóa theo từng ca'],
    feedback: 'Nhà trường và sinh viên đánh giá 5 sao phần kỹ thuật.',
    related: ['dem-hoi-happy-christmas.html', 'dem-hoi-chao-tan-sinh-vien-k70.html', 'dem-nhac-gieo-yeu-thuong.html'],
  }),

  P({
    file: 'dem-hoi-chao-tan-sinh-vien-k70.html',
    pool: 'concert',
    titlePlain: 'Đêm hội chào tân sinh viên K70 — Hoàng Tôn, Mason, DJ Jim | FT GROUP E&E',
    descPlain: 'Đại nhạc hội K70: Hoàng Tôn, Rapper Mason Nguyễn, MC Hype Minami, DJ Jim — không khí bùng nổ.',
    keywords: 'K70, Hoàng Tôn, Mason Nguyễn, MC Minami, DJ Jim, FT GROUP E&E',
    filters: ['dai-nhac-hoi', 'chao-tan-sinh-vien'],
    cardTitle: 'Chào TSV K70',
    cardCat: 'Đại nhạc hội · Chào tân',
    cardDesc: 'DJ + rap + hype MC — đêm bùng nổ.',
    cat: 'Đại nhạc hội / Chào tân sinh viên',
    loc: 'Học viện Nông nghiệp Việt Nam',
    h1: 'Đêm hội chào tân sinh viên K70',
    overview: {
      name: 'Chào TSV K70',
      client: 'HVNN Việt Nam',
      place: 'Học viện Nông nghiệp Việt Nam',
      time: 'Lịch Đoàn — Hội',
      scale: 'Đại nhạc hội sân trường',
      services: 'Sân khấu concert, DJ booth, sub, beam, crew âm thanh',
    },
    intros: [
      { h: 'Line-up', p: 'Hoàng Tôn, Mason Nguyễn, MC Hype Minami, DJ Jim.' },
      { h: 'Không khí', p: 'Hype liên tục — ánh sáng pulse, laser/smoke theo quy định địa điểm.' },
      { h: 'Vận hành', p: 'Phối hợp DJ & ban nhạc, cue đèn chính xác.' },
    ],
    quote: 'Sân nổ tung — bass đủ mạnh mà vẫn kiểm soát được.',
    cite: 'Phản hồi sau show',
    results: ['Ổn định suốt set DJ', 'Rap & vocal balance', 'Khán đài an toàn'],
    experienceBullets: ['Mosh pit tinh thần — không khí festival', 'MC kéo tương tác liên tục'],
    feedback: 'BTC và nghệ sĩ khen crew kỹ thuật.',
    related: ['dem-hoi-chao-tan-sinh-vien-k69.html', 'dai-nhac-hoi-chao-tan-sinh-vien-cdltk.html', 'dem-hoi-chao-tan-sinh-vien-khoa-du-lich.html'],
  }),

  P({
    file: 'le-ky-niem-ngay-nha-giao-viet-nam.html',
    pool: 'school',
    titlePlain: 'Lễ kỉ niệm Ngày Nhà giáo Việt Nam — Khoa Chăn nuôi HVNN | FT GROUP E&E',
    descPlain: 'Sự kiện trường học tri ân thầy cô tại Khoa Chăn nuôi, Học viện Nông nghiệp Việt Nam.',
    keywords: '20/11, nhà giáo Việt Nam, HVNN, FT GROUP E&E',
    filters: ['su-kien-truong-hoc'],
    cardTitle: 'Lễ 20/11 Khoa Chăn nuôi',
    cardCat: 'Sự kiện trường học · Lễ kỷ niệm',
    cardDesc: 'Tri ân thầy cô — trang trọng và cảm động.',
    cat: 'Lễ kỷ niệm / Sự kiện trường học',
    loc: 'Khoa Chăn nuôi — Học viện Nông nghiệp Việt Nam',
    h1: 'Lễ kỉ niệm Ngày Nhà giáo Việt Nam',
    overview: {
      name: 'Ngày Nhà giáo tại Khoa Chăn nuôi',
      client: 'Khoa Chăn nuôi — HVNN',
      place: 'Học viện Nông nghiệp Việt Nam',
      time: '20/11 (theo năm)',
      scale: 'Buổi lễ — văn nghệ',
      services: 'Sân khấu, âm thanh hội trường, đèn, backdrop',
    },
    intros: [
      { h: 'Không khí', p: 'Tôn vinh nhà giáo với phần lễ trang trọng và tiết mục tri ân.' },
      { h: 'Dựng chương trình', p: 'Timeline gọn, mic dàn cho diễn giả và múa hát.' },
      { h: 'Hậu kỳ', p: 'Thu dọn nhanh, bàn giao mặt bằng sạch.' },
    ],
    quote: 'Không khí xúc động và trang trọng.',
    cite: 'Ban giám hiệu khoa',
    results: ['Đúng nghi thức', 'Âm thanh rõ lời phát biểu', 'Không gian ấm'],
    experienceBullets: ['Sinh viên tặng hoa, vỗ tay', 'Không khí tri ân'],
    feedback: 'Thầy cô đánh giá cao phần âm thanh và ánh sáng.',
    related: ['ngay-hoi-chung-toi-la-chien-si.html', 'dem-hoi-chao-tan-sinh-vien-khoa-du-lich.html', 'dem-hoi-happy-christmas.html'],
  }),

  P({
    file: 'chuong-trinh-khai-truong-tong-hop.html',
    pool: 'opening',
    titlePlain: 'Các chương trình khai trương — doanh nghiệp, trường học, bệnh viện | FT GROUP E&E',
    descPlain: 'Tổng hợp dự án khai trương: ribbon cutting, balloon, lion dance, sân khấu — FT GROUP E&E.',
    keywords: 'khai trương, ribbon cutting, múa lân, FT GROUP E&E',
    filters: ['khai-truong'],
    cardTitle: 'Khai trương tổng hợp',
    cardCat: 'Khai trương',
    cardDesc: 'Doanh nghiệp, trường, bệnh viện — sân khấu & lễ cắt băng.',
    cat: 'Khai trương',
    loc: 'Miền Bắc (theo từng dự án)',
    h1: 'Các chương trình khai trương',
    overview: {
      name: 'Khai trương đa ngành',
      client: 'Doanh nghiệp / Trường học / Bệnh viện (theo hợp đồng)',
      place: 'Theo địa điểm từng dự án',
      time: 'Lịch riêng',
      scale: 'Từ lễ nhỏ đến khai trương quy mô',
      services: 'Ribbon, balloon garland, múa lân, sân khấu, backdrop, MC',
    },
    intros: [
      { h: 'Phong cách', p: 'Backdrop sang, cổng chào, điểm chụp ribbon cutting rõ key visual.' },
      { h: 'Nghi thức', p: 'Tôn trọng timeline cắt băng, đón khách VIP, chụp báo chí.' },
      { h: 'Kỹ thuật', p: 'Âm thanh rõ lời phát biểu; ánh sáng phù hợp chụp ảnh.' },
    ],
    quote: 'Khai trương đúng “phút vàng” và hình ảnh đẹp.',
    cite: 'Khách hàng doanh nghiệp',
    results: ['Nhiều dự án repeat', 'Full package trọn gói', 'Tư vấn concept theo ngành'],
    experienceBullets: ['Khách check-in xếp hàng cổng decor', 'Lễ cắt băng gọn trong slot'],
    feedback: 'Đối tác khen phần MC, trang trí và kỹ thuật.',
    related: ['thiet-bi-su-kien-showcase.html', 'teambuilding-vietinbank-bac-giang.html', 'dai-nhac-hoi-chao-tan-sinh-vien-cdltk.html'],
  }),

  P({
    file: 'ngay-hoi-trai-nghiem-chien-si-nhi.html',
    pool: 'preschool',
    titlePlain: 'Ngày hội trải nghiệm Chiến sĩ nhí — mầm non | FT GROUP E&E',
    descPlain: 'Ngày hội trải nghiệm an toàn — hoạt động vui chơi có chủ đề cho mầm non.',
    keywords: 'ngày hội trải nghiệm, mầm non, FT GROUP E&E',
    filters: ['trai-nghiem-giao-duc'],
    cardTitle: 'Chiến sĩ nhí',
    cardCat: 'Ngày hội trải nghiệm · Mầm non',
    cardDesc: 'Trò chơi nhẹ, an toàn — không gian màu sắc.',
    cat: 'Ngày hội trải nghiệm / Mầm non',
    loc: 'Theo lịch trường mầm non (miền Bắc)',
    h1: 'Ngày hội trải nghiệm “Chiến sĩ nhí”',
    overview: {
      name: 'Chiến sĩ nhí',
      client: 'Trường hợp tác mầm non',
      place: 'Sân trường / hội trường',
      time: 'Niên học',
      scale: 'Học sinh + phụ huynh',
      services: 'Kịch bản game, âm thanh vừa phải, đạo cụ, nhân sự sự kiện',
    },
    intros: [
      { h: 'Mục tiêu', p: 'Rèn thói quen qua trò chơi — không gay cấn, phù hợp lứa tuổi.' },
      { h: 'An toàn', p: 'Check kỹ vật liệu, luồng di chuyển, micro tần phù hợp.' },
      { h: 'Không khí', p: 'Màu sắc, nhạc vui, hướng dẫn viên gần gũi.' },
    ],
    quote: 'Các con vui hết mình, phụ huynh yên tâm.',
    cite: 'Giáo viên chủ nhiệm',
    results: ['Không tai nạn nhỏ', 'Tham gia tích cực', 'Feedback tốt'],
    experienceBullets: ['Phụ huynh chụp ảnh check-in', 'Trẻ tham gia đồng loạt'],
    feedback: 'Trường book lại năm sau.',
    related: ['ngay-hoi-cung-con-kham-pha.html', 'chuong-trinh-cuoc-dua-ki-thu.html', 'chuong-trinh-le-hoi-nuoc-2.html'],
  }),

  P({
    file: 'ngay-hoi-chung-toi-la-chien-si.html',
    pool: 'school',
    titlePlain: 'Ngày hội Chúng tôi là chiến sĩ — THCS | FT GROUP E&E',
    descPlain: 'Ngày hội trải nghiệm cấp THCS — gắn kết, kỷ luật nhẹ, hoạt động tập thể.',
    keywords: 'THCS, ngày hội trường, FT GROUP E&E',
    filters: ['trai-nghiem-giao-duc', 'su-kien-truong-hoc'],
    cardTitle: 'Chúng tôi là chiến sĩ',
    cardCat: 'Ngày hội trải nghiệm · THCS',
    cardDesc: 'Đồng đội & tinh thần — sân chơi an toàn.',
    cat: 'Ngày hội trải nghiệm / THCS',
    loc: 'Trường THCS (theo chương trình)',
    h1: 'Ngày hội “Chúng tôi là chiến sĩ”',
    overview: {
      name: 'Chiến sĩ THCS',
      client: 'Trường THCS đối tác',
      place: 'Sân trường',
      time: 'Học kỳ',
      scale: 'Khối THCS',
      services: 'MC, game station, âm thanh sân, cổng chào',
    },
    intros: [
      { h: 'Concept', p: 'Tăng gắn kết lớp — luật chơi rõ, không đụng chạm thể lực quá mức.' },
      { h: 'Tổ chức', p: 'Chia đội, bảng điểm, nhạc nền động.' },
      { h: 'Hậu kỳ', p: 'Tổng kết nhanh, trao giải phong trào.' },
    ],
    quote: 'Các em háo hức tham gia từng trạm.',
    cite: 'Tổng phụ trách Đội',
    results: ['Kỷ luật tốt', 'Vui', 'Không sự cố'],
    experienceBullets: ['Đồng phục đội rõ màu', 'Khán đài cổ vũ'],
    feedback: 'Nhà trường muốn giữ format cho năm sau.',
    related: ['ngay-hoi-trai-nghiem-chien-si-nhi.html', 'chuyen-de-phong-chay-chua-chay.html', 'le-ky-niem-ngay-nha-giao-viet-nam.html'],
  }),

  P({
    file: 'ngay-hoi-le-hoi-nuoc.html',
    pool: 'waterplay',
    titlePlain: 'Ngày hội Lễ hội nước — mầm non | FT GROUP E&E',
    descPlain: 'Chương trình lễ hội nước an toàn cho mầm non — FT GROUP E&E đồng hành thiết bị & nhân sự.',
    keywords: 'lễ hội nước, mầm non, FT GROUP E&E',
    filters: ['trai-nghiem-giao-duc'],
    cardTitle: 'Lễ hội nước',
    cardCat: 'Ngày hội trải nghiệm · Mầm non',
    cardDesc: 'Splash party có kiểm soát — vui và mát.',
    cat: 'Ngày hội trải nghiệm / Mầm non',
    loc: 'Theo sân trường (miền Bắc)',
    h1: 'Ngày hội “Lễ hội nước”',
    overview: {
      name: 'Lễ hội nước (bản 1)',
      client: 'Trường mầm non',
      place: 'Sân trường',
      time: 'Mùa hè',
      scale: 'Học sinh + PH',
      services: 'Khu vực nước, máy bơm, nhân sự giữ an toàn, nhạc',
    },
    intros: [
      { h: 'An toàn', p: 'SOP nước, chống trơn, phân luồng vào/ra.' },
      { h: 'Vui', p: 'Trò nhẹ, màu sắc, MC dẫn nhịp.' },
      { h: 'Kỹ thuật', p: 'Che máy, cáp điện xa khu ướt.' },
    ],
    quote: 'Trẻ cười suốt buổi — phụ huynh đứng ngoài vẫn thấy rõ luồng.',
    cite: 'Ban giám hiệu',
    results: ['Không sự cố', 'Phản hồi tốt', 'Lặp lại hằng năm'],
    experienceBullets: ['Ảnh kỉ niệm ướt áo đồng phục', 'Bé thích trạm phun nước'],
    feedback: 'Đội triển khai chuyên nghiệp.',
    related: ['chuong-trinh-le-hoi-nuoc-2.html', 'ngay-hoi-trai-nghiem-chien-si-nhi.html', 'ngay-hoi-cung-con-kham-pha.html'],
  }),

  P({
    file: 'ngay-hoi-cung-con-kham-pha.html',
    pool: 'preschool',
    titlePlain: 'Ngày hội Cùng con khám phá — mầm non | FT GROUP E&E',
    descPlain: 'Ngày hội khám phá cùng phụ huynh — trạm trải nghiệm, decor thân thiện.',
    keywords: 'mầm non, ngày hội gia đình, FT GROUP E&E',
    filters: ['trai-nghiem-giao-duc'],
    cardTitle: 'Cùng con khám phá',
    cardCat: 'Ngày hội trải nghiệm · Mầm non',
    cardDesc: 'Phụ huynh đồng hành — trạm học chơi.',
    cat: 'Ngày hội trải nghiệm / Mầm non',
    loc: 'Trường / đối tác FT',
    h1: 'Ngày hội “Cùng con khám phá”',
    overview: {
      name: 'Cùng con khám phá',
      client: 'Trường MN',
      place: 'Sân trường',
      time: 'Theo lịch',
      scale: 'PH + học sinh',
      services: 'Booth trạm, nhạc, hướng dẫn, decor',
    },
    intros: [
      { h: 'Ý tưởng', p: 'Mỗi trạm một chủ đề khoa học nhẹ nhàng.' },
      { h: 'Trải nghiệm', p: 'Phụ huynh làm cùng con — tăng gắn kết.' },
      { h: 'Setup', p: 'Bàn ghế thấp, an toàn góc cạnh.' },
    ],
    quote: 'Gia đình tham gia nhiệt tình.',
    cite: 'BTC',
    results: ['Tương tác cao', 'Ảnh đẹp', 'Thu dọn nhanh'],
    experienceBullets: ['Trạm chơi có hướng dẫn', 'Check-in gia đình'],
    feedback: 'Trường tiếp tục tin tưởng FT.',
    related: ['ngay-hoi-trai-nghiem-chien-si-nhi.html', 'chuong-trinh-cuoc-dua-ki-thu.html', 'ngay-hoi-le-hoi-nuoc.html'],
  }),

  P({
    file: 'chuyen-de-phong-chay-chua-chay.html',
    pool: 'elementary',
    titlePlain: 'Chuyên đề phòng cháy chữa cháy — tiểu học | FT GROUP E&E',
    descPlain: 'Chuyên đề an toàn PCCC cho tiểu học — mô hình, hướng dẫn, minh họa.',
    keywords: 'PCCC trường học, tiểu học, FT GROUP E&E',
    filters: ['trai-nghiem-giao-duc'],
    cardTitle: 'Chuyên đề PCCC',
    cardCat: 'Ngày hội trải nghiệm · Tiểu học',
    cardDesc: 'Kiến thức an toàn qua hoạt động.',
    cat: 'Ngày hội trải nghiệm / Tiểu học',
    loc: 'Trường tiểu học (miền Bắc)',
    h1: 'Chuyên đề “Phòng cháy chữa cháy”',
    overview: {
      name: 'PCCC tiểu học',
      client: 'Trường tiểu học',
      place: 'Hội trường / sân',
      time: 'Theo lịch',
      scale: 'Cả khối',
      services: 'Kịch bản, âm thanh, mô hình minh họa, MC',
    },
    intros: [
      { h: 'Giáo dục', p: 'Ngôn ngữ phù hợp lứa tuổi — nhấn thoát hiểm, gọi cứu hỏa.' },
      { h: 'Minh họa', p: 'Trạm mô phỏng, đường thoát hiểm mô phỏng.' },
      { h: 'An toàn', p: 'Không dùng lửa thật gần trẻ; video/đạo cụ an toàn.' },
    ],
    quote: 'HS nhớ quy trình 4 bước rõ ràng.',
    cite: 'Tổ phụ trách',
    results: ['Tăng nhận thức', 'Đánh giá sau khảo sát tốt'],
    experienceBullets: ['Thầy cô đồng hành từng lớp', 'Hỏi đáp cuối buổi'],
    feedback: 'Hiệu trưởng muốn lặp lại mỗi năm.',
    related: ['chuyen-de-gia-dinh-yeu-thuong.html', 'chuyen-de-khoa-hoc-dieu-ki-a.html', 'ngay-hoi-chung-toi-la-chien-si.html'],
  }),

  P({
    file: 'chuyen-de-gia-dinh-yeu-thuong.html',
    pool: 'elementary',
    titlePlain: 'Chuyên đề Gia đình yêu thương — tiểu học | FT GROUP E&E',
    descPlain: 'Chương trình kết nối gia đình — hoạt động cảm xúc, game nhẹ.',
    keywords: 'gia đình yêu thương, tiểu học, FT GROUP E&E',
    filters: ['trai-nghiem-giao-duc'],
    cardTitle: 'Gia đình yêu thương',
    cardCat: 'Ngày hội trải nghiệm · Tiểu học',
    cardDesc: 'Cảm xúc & kết nối PH — học sinh.',
    cat: 'Ngày hội trải nghiệm / Tiểu học',
    loc: 'Trường tiểu học',
    h1: 'Chuyên đề “Gia đình yêu thương”',
    overview: {
      name: 'Gia đình yêu thương',
      client: 'Trường TH',
      place: 'Hội trường',
      time: 'Niên học',
      scale: 'HS + PH',
      services: 'Kịch bản cảm xúc, nhạc, backdrop, tổ chức game',
    },
    intros: [
      { h: 'Mục tiêu', p: 'Tăng hiểu biết lẫn nhau trong gia đình.' },
      { h: 'Hoạt động', p: 'Thư đi, game nhóm nhỏ, chia sẻ trên sân khấu nhẹ.' },
      { h: 'Không khí', p: 'Nhạc ấm, ánh sáng dịu.' },
    ],
    quote: 'Nhiều phụ huynh xúc động.',
    cite: 'GVCN',
    results: ['Feedback PH tích cực', 'Không quá tải thời lượng'],
    experienceBullets: ['PH ôm con lên stage game nhỏ'],
    feedback: 'BTC muốn giữ format cho khối khác.',
    related: ['chuyen-de-phong-chay-chua-chay.html', 'chuyen-de-khoa-hoc-dieu-ki-b.html', 'ngay-hoi-cung-con-kham-pha.html'],
  }),

  P({
    file: 'chuyen-de-khoa-hoc-dieu-ki-a.html',
    pool: 'elementary',
    titlePlain: 'Chuyên đề Khoa học diệu kì — tiểu học (lớp 1) | FT GROUP E&E',
    descPlain: 'Chuyên đề STEM nhẹ — quan sát, thí nghiệm demo an toàn cho tiểu học.',
    keywords: 'khoa học diệu kỳ, STEM, FT GROUP E&E',
    filters: ['trai-nghiem-giao-duc'],
    cardTitle: 'Khoa học diệu kì · A',
    cardCat: 'Ngày hội trải nghiệm · Tiểu học',
    cardDesc: 'Thí nghiệm demo — dễ hiểu, an toàn.',
    cat: 'Ngày hội trải nghiệm / Tiểu học',
    loc: 'Trường tiểu học (lớp ghép A)',
    h1: 'Chuyên đề “Khoa học diệu kì” (đợt A)',
    overview: {
      name: 'Khoa học diệu kì — đợt A',
      client: 'Trường tiểu học',
      place: 'Phòng học / sân',
      time: 'Học kỳ',
      scale: 'Khối lớp',
      services: 'Bàn thí nghiệm, micro, slide, hướng dẫn',
    },
    intros: [
      { h: 'Nội dung', p: 'Hiện tượng vật lí đơn giản, quan sát màu, phản ứng an toàn.' },
      { h: 'An toàn', p: 'Hoá chất food-grade / hoặc chỉ demo video + mô hình.' },
      { h: 'Tương tác', p: 'HS lên thử trải nghiệm có giám sát.' },
    ],
    quote: 'Trẻ hỏi liên tục — tốt cho tư duy.',
    cite: 'Giáo viên Tự nhiên',
    results: ['Tham gia 100%', 'Hiểu khái niệm cơ bản'],
    experienceBullets: ['Bang màu chữ A', 'Thí nghiệm nước trong khay'],
    feedback: 'Phụ huynh khen phần minh họa.',
    related: ['chuyen-de-khoa-hoc-dieu-ki-b.html', 'chuyen-de-phong-chay-chua-chay.html', 'chuong-trinh-cuoc-dua-ki-thu.html'],
  }),

  P({
    file: 'chuyen-de-khoa-hoc-dieu-ki-b.html',
    pool: 'elementary',
    titlePlain: 'Chuyên đề Khoa học diệu kì — tiểu học (lớp 2) | FT GROUP E&E',
    descPlain: 'Phiên bản triển khai thứ hai — nội dung mở rộng theo độ tuổi.',
    keywords: 'khoa học, trải nghiệm, FT GROUP E&E',
    filters: ['trai-nghiem-giao-duc'],
    cardTitle: 'Khoa học diệu kì · B',
    cardCat: 'Ngày hội trải nghiệm · Tiểu học',
    cardDesc: 'Đợt B — nội dung nâng theo lớp.',
    cat: 'Ngày hội trải nghiệm / Tiểu học',
    loc: 'Trường tiểu học (lớp ghép B)',
    h1: 'Chuyên đề “Khoa học diệu kì” (đợt B)',
    overview: {
      name: 'Khoa học diệu kì — đợt B',
      client: 'Cùng hệ thống / khối khác',
      place: 'Trường',
      time: 'Học kỳ',
      scale: 'Khối lớp',
      services: 'Giống đợt A — tùy chỉnh độ khó bài lab',
    },
    intros: [
      { h: 'Khác biệt', p: 'Thêm trạm robot demo / pin mặt trời mô phỏng.' },
      { h: 'Kỹ thuật', p: 'Cùng SOP an toàn như đợt A.' },
      { h: 'Kết quả', p: 'HS trả lời câu hỏi tương tác cuối giờ.' },
    ],
    quote: 'Đợt B giữ được sự tập trung cao.',
    cite: 'BTC',
    results: ['Điểm tương tác cuối giờ cao'],
    experienceBullets: ['HS thích trạm robot hơn'],
    feedback: 'Nhà trường hài lòng.',
    related: ['chuyen-de-khoa-hoc-dieu-ki-a.html', 'chuyen-de-gia-dinh-yeu-thuong.html', 'chuyen-de-phong-chay-chua-chay.html'],
  }),

  P({
    file: 'chuong-trinh-le-hoi-nuoc-2.html',
    pool: 'waterplay',
    titlePlain: 'Chương trình Lễ hội nước — mầm non | FT GROUP E&E',
    descPlain: 'Phiên triển khai chương trình Lễ hội nước (bản 2) — cùng format an toàn.',
    keywords: 'lễ hội nước, mầm non, FT GROUP E&E',
    filters: ['trai-nghiem-giao-duc'],
    cardTitle: 'Lễ hội nước (chương trình)',
    cardCat: 'Ngày hội trải nghiệm · Mầm non',
    cardDesc: 'Chương trình đã chứng minh — lặp tại trường khác.',
    cat: 'Ngày hội trải nghiệm / Mầm non',
    loc: 'Theo hợp đồng',
    h1: 'Chương trình “Lễ hội nước”',
    overview: {
      name: 'Lễ hội nước — gói chương trình',
      client: 'Trường MN đối tác',
      place: 'Sân trường',
      time: 'Mùa hè',
      scale: 'Full khối',
      services: 'Full setup khu nước + crew giữ trật tự',
    },
    intros: [
      { h: 'Scale', p: 'Nhiều trường đã triển khai — checklist chuẩn FT.' },
      { h: 'Sự khác biệt', p: 'Tùy sân mà bố trí lượng vòi phun.' },
      { h: 'Cam kết', p: 'An toàn đặt trên hết.' },
    ],
    quote: 'PH yên tâm đứng rào quan sát.',
    cite: 'Hiệu trưởng',
    results: ['0 sự cố', 'Book lại'],
    experienceBullets: ['Cổng check-in nhanh'],
    feedback: 'FT được giới thiệu sang trường bạn.',
    related: ['ngay-hoi-le-hoi-nuoc.html', 'ngay-hoi-trai-nghiem-chien-si-nhi.html', 'ngay-hoi-cung-con-kham-pha.html'],
  }),

  P({
    file: 'chuong-trinh-cuoc-dua-ki-thu.html',
    pool: 'preschool',
    titlePlain: 'Chương trình Cuộc đua kì thú — mầm non | FT GROUP E&E',
    descPlain: 'Trò chơi vận động nhẹ — chủ đề phiêu lưu an toàn cho lứa mầm non.',
    keywords: 'mầm non, trò chơi, FT GROUP E&E',
    filters: ['trai-nghiem-giao-duc'],
    cardTitle: 'Cuộc đua kì thú',
    cardCat: 'Ngày hội trải nghiệm · Mầm non',
    cardDesc: 'Đường đua mềm — mascot dẫn đội.',
    cat: 'Ngày hội trải nghiệm / Mầm non',
    loc: 'Sân trường',
    h1: 'Chương trình “Cuộc đua kì thú”',
    overview: {
      name: 'Cuộc đua kì thú',
      client: 'Trường MN',
      place: 'Sân',
      time: 'Sự kiện năm học',
      scale: 'Cả trường chia ca',
      services: 'Trạm game, rào chắn mềm, nhạc, MC hoạt hình',
    },
    intros: [
      { h: 'An toàn', p: 'Không cạnh tranh căng; tập thể vui.' },
      { h: 'Màu sắc', p: 'Backrop chủ đề rừng/đường đua mềm.' },
      { h: 'Vận hành', p: 'Nhân sự mỗi trạm giữ luồng.' },
    ],
    quote: 'Bé cười suốt đường đua.',
    cite: 'Cô giáo',
    results: ['Vui', 'An toàn', 'Hình ảnh đẹp'],
    experienceBullets: ['Mascot chụp ảnh cùng bé'],
    feedback: 'Trường muốn giữ mascot cùng concept.',
    related: ['ngay-hoi-trai-nghiem-chien-si-nhi.html', 'chuong-trinh-le-hoi-nuoc-2.html', 'ngay-hoi-cung-con-kham-pha.html'],
  }),

  P({
    file: 'teambuilding-vietinbank-bac-giang.html',
    pool: 'team',
    titlePlain: 'Teambuilding Vietinbank Bắc Giang | FT GROUP E&E',
    descPlain: 'Outdoor team building — cán bộ CNV Vietinbank Bắc Giang; trò chơi nhóm, gắn kết.',
    keywords: 'teambuilding, Vietinbank, Bắc Giang, FT GROUP E&E',
    filters: ['team-building'],
    cardTitle: 'TB Vietinbank Bắc Giang',
    cardCat: 'Team Building',
    cardDesc: 'Outdoor — game nhóm & bonding công ty.',
    cat: 'Team Building doanh nghiệp',
    loc: 'Bắc Giang',
    h1: 'Teambuilding Vietinbank Bắc Giang',
    overview: {
      name: 'TB Vietinbank BG',
      client: 'Vietinbank chi nhánh Bắc Giang',
      place: 'Địa điểm outdoor theo hợp đồng',
      time: 'Theo lịch DN',
      scale: 'Cán bộ CNV',
      services: 'Facilitator, trò chơi, âm thanh sân, sân khấu nhỏ',
    },
    intros: [
      { h: 'Mục tiêu', p: 'Tăng gắn kết phòng ban sau giờ làm.' },
      { h: 'Hoạt động', p: 'Ice-break, chiến thuật nhóm, tổng kết vui.' },
      { h: 'Logistics', p: 'Sound outdoor, che nắng, nước uống, y tế sơ cấp.' },
    ],
    quote: 'Thắng thua đều vui — quan trọng là đồng đội cười nhiều.',
    cite: 'HR',
    results: ['Engagement cao', 'Không chấn thương', 'Survey nội bộ tốt'],
    experienceBullets: ['Ảnh flycam tập thể', 'Trò cười đồng loạt'],
    feedback: 'Phòng nhân sự book lại.',
    related: ['teambuilding-nha-khoa-nhu-ngoc.html', 'chuong-trinh-khai-truong-tong-hop.html', 'thiet-bi-su-kien-showcase.html'],
  }),

  P({
    file: 'teambuilding-nha-khoa-nhu-ngoc.html',
    pool: 'team',
    titlePlain: 'Teambuilding Nha khoa Như Ngọc | FT GROUP E&E',
    descPlain: 'Teambuilding nội bộ phòng khám — chuyên nghiệp, gọn, đúng timeline.',
    keywords: 'teambuilding nha khoa, FT GROUP E&E',
    filters: ['team-building'],
    cardTitle: 'TB Nha khoa Như Ngọc',
    cardCat: 'Team Building',
    cardDesc: 'Gắn kết đội ngũ y bác sĩ & hành chính.',
    cat: 'Team Building doanh nghiệp',
    loc: 'Hà Nội / vùng phụ cận',
    h1: 'Teambuilding Nha khoa Như Ngọc',
    overview: {
      name: 'TB Nha khoa Như Ngọc',
      client: 'Phòng khám Nha khoa Như Ngọc',
      place: 'Địa điểm gọn trong ngày',
      time: 'Theo lịch',
      scale: 'Toàn bộ nhân sự',
      services: 'Facilitator, game nhóm nhỏ, MC, nhạc nền',
    },
    intros: [
      { h: 'Đặc thù', p: 'Khung giờ gắn lịch khám — setup nhanh.' },
      { h: 'Nội dung', p: 'Game nhẹ không ảnh hưởng tay nghề ngày sau.' },
      { h: 'Tinh thần', p: 'Nhấn hợp tác giữa lễ tân — bác sĩ.' },
    ],
    quote: 'Tập thể gần nhau hơn sau 1 buổi chiều.',
    cite: 'Quản lý phòng khám',
    results: ['Không ảnh hưởng lịch hẹn', 'Team feedback 4.8/5'],
    experienceBullets: ['Chụp ảnh đồng phục đẹp'],
    feedback: 'Giới thiệu cho phòng khám khác.',
    related: ['teambuilding-vietinbank-bac-giang.html', 'chuong-trinh-khai-truong-tong-hop.html', 'thiet-bi-su-kien-showcase.html'],
  }),

  P({
    file: 'thiet-bi-su-kien-showcase.html',
    pool: 'equipment',
    titlePlain: 'Thiết bị sự kiện — âm thanh, ánh sáng, LED | FT GROUP E&E',
    descPlain: 'Tổng hợp năng lực thiết bị: âm thanh, ánh sáng, sân khấu, LED, photobooth, check-in, 3D, giáo cụ, TB, cổng hơi.',
    keywords: 'cho thuê thiết bị sự kiện, LED, FT GROUP E&E',
    filters: ['thiet-bi-su-kien'],
    cardTitle: 'Thiết bị sự kiện',
    cardCat: 'Thiết bị',
    cardDesc: 'Full catalog — lắp đặt & vận hành kỹ thuật.',
    cat: 'Thiết bị sự kiện',
    loc: 'Kho & vận chuyển miền Bắc',
    h1: 'Thiết bị sự kiện — catalog triển khai',
    overview: {
      name: 'Gói thiết bị FT',
      client: 'Nhiều đối tác / sự kiện',
      place: 'Theo địa điểm job',
      time: '365 ngày',
      scale: 'Từ job nhỏ đến festival',
      services: 'Âm thanh, ánh sáng, LED, sân khấu, photobooth, check-in, 3D mapping, giáo cụ TE, cổng hơi',
    },
    intros: [
      { h: 'Catalog', p: 'Line array, sub, beam, wash, LED indoor/outdoor, truss, máy bơm sương, backdrop.' },
      { h: 'Vận hành', p: 'Kỹ thuật viên onsite, checklist, backup thiết bị.' },
      { h: 'Trải nghiệm', p: 'Đồng bộ creative và an toàn tải điện.' },
    ],
    quote: 'Một đầu mối thiết bị — giảm rủi ro đối tác.',
    cite: 'Quản lý kỹ thuật FT',
    results: ['Bảo trì trước job', 'Biên bản bàn giao rõ'],
    experienceBullets: ['Khách xem dry-run trước giờ G'],
    feedback: 'Đối tác sản xuất show tin tưởng lineup máy.',
    related: ['dai-nhac-hoi-chao-tan-sinh-vien-cdltk.html', 'chuong-trinh-khai-truong-tong-hop.html', 'teambuilding-vietinbank-bac-giang.html'],
  }),
];
