import { getGallery, heroFromPool } from './gallery-pools.mjs';

function P(x) {
  const pool = x.pool || 'concert';
  const gallery = x.gallery || getGallery(pool);
  const hero = x.hero || heroFromPool(pool);
  return {
    ...x,
    hero,
    gallery,
    thumb: x.thumb || hero,
  };
}

export const PROJECTS = [
  P({
    file: 'dem-hoi-chao-tan-sinh-vien-k69.html',
    pool: 'concert',
    titlePlain: 'Đêm hội chào tân sinh viên K69 — Học viện Nông nghiệp | FT GROUP E&E',
    descPlain:
      'Đại nhạc hội chào K69 tại Học viện Nông nghiệp Việt Nam: Tiên Tiên, Thanh Hưng; sân khấu âm thanh ánh sáng chuyên nghiệp.',
    keywords: 'chào tân sinh viên, đại nhạc hội, Học viện Nông nghiệp, FT GROUP E&E, sự kiện Hà Nội',
    filters: ['dai-nhac-hoi', 'chao-tan-sinh-vien'],
    cardTitle: 'Đêm hội chào TSV K69',
    cardCat: 'Đại nhạc hội · Chào tân sinh viên',
    cardDesc: 'Tiên Tiên & Thanh Hưng — không khí bùng nổ, sân khấu chuẩn concert.',
    cat: 'Đại nhạc hội / Chào tân sinh viên',
    loc: 'Học viện Nông nghiệp Việt Nam',
    h1: 'Đ&ecirc;m hội ch&agrave;o t&acirc;n sinh vi&ecirc;n K69',
    overview: {
      name: 'Đêm hội chào tân sinh viên K69',
      client: 'Học viện Nông nghiệp Việt Nam',
      place: 'Học viện Nông nghiệp Việt Nam (Trâu Quỳ, Gia L&acirc;m, H&agrave; Nội)',
      time: 'Theo lịch Đoàn — Hội sinh viên',
      scale: 'Đại nhạc hội s&acirc;n trường &mdash; quy m&ocirc; lớn',
      services: 'S&acirc;n khấu, line array, beam, LED, MC/DJ, điều phối, kỹ thuật &acirc;m thanh &aacute;nh s&aacute;ng',
    },
    intros: [
      { h: 'Mục ti&ecirc;u chương tr&igrave;nh', p: 'Ch&agrave;o kh&oacute;a mới với kh&ocirc;ng kh&iacute; trẻ, s&ocirc;i động &mdash; kết nối t&acirc;n sinh vi&ecirc;n với đời sống Đo&agrave;n, Hội v&agrave; nh&agrave; trường.' },
      { h: 'Nội dung nổi bật', p: 'Ca sĩ kh&aacute;ch mời: Ti&ecirc;n Ti&ecirc;n v&agrave; Thanh Hưng; d&agrave;n dựng &acirc;m thanh &aacute;nh s&aacute;ng professional để đảm bảo trải nghiệm concert.' },
      { h: 'Ph&iacute;a FT GROUP E&E', p: 'Thiết kế s&acirc;n khấu, timing, backup m&aacute;y ph&aacute;t &mdash; vận h&agrave;nh li&ecirc;n tục suốt đ&ecirc;m nhạc.' },
    ],
    quote: 'Kh&aacute;n đ&agrave;i h&oacute;t theo từng b&agrave;i &mdash; &acirc;m thanh r&otilde;, d&agrave;n đ&egrave;n đ&uacute;ng nhịp show.',
    cite: 'Phản hồi BTC sinh viên',
    results: [
      'S&acirc;n khấu vận h&agrave;nh ổn định suốt đ&ecirc;m',
      'Kh&ocirc;ng gi&aacute;n trẻ trung, check-in &amp; cổng ch&agrave;o gọn g&agrave;ng',
      'Đồng bộ MC v&agrave; tiết mục kh&aacute;ch mời',
    ],
    experienceBullets: [
      'Sinh vi&ecirc;n tập trung đ&ocirc;ng, kh&ocirc;ng kh&iacute; cuồng nhiệt như festival.',
      'D&agrave;n light chase theo beat &mdash; cảm gi&aacute;c concert thực thụ.',
    ],
    experienceQuote: 'Đ&ecirc;m như một show lớn ngay tại s&acirc;n trường.',
    feedback: 'BTC đ&aacute;nh gi&aacute; cao phần kỹ thuật &acirc;m thanh v&agrave; phối hợp với nghệ sĩ.',
    related: ['dem-hoi-chao-tan-sinh-vien-k70.html', 'dai-nhac-hoi-chao-tan-sinh-vien-cdltk.html', 'dem-hoi-chao-tan-sinh-vien-khoa-du-lich.html'],
  }),

  P({
    file: 'dem-hoi-chao-tan-sinh-vien-khoa-du-lich.html',
    pool: 'concert',
    titlePlain: 'Đêm hội chào tân sinh viên Khoa Du lịch — HVNN Việt Nam | FT GROUP E&E',
    descPlain: 'Chương trình chào tân Khoa Du lịch; Học viện Nông nghiệp Việt Nam. Tổ chức FT GROUP E&E.',
    keywords: 'chào tân sinh viên, Khoa Du lịch, HVNN, FT GROUP E&E',
    filters: ['chao-tan-sinh-vien'],
    cardTitle: 'Chào TSV Khoa Du lịch',
    cardCat: 'Chào tân sinh viên',
    cardDesc: 'Gắn kết tân sinh viên Khoa Du lịch — bản sắc trẻ, sân khấu gọn.',
    cat: 'Chào tân sinh viên',
    loc: 'Học viện Nông nghiệp Việt Nam',
    h1: 'Đ&ecirc;m hội ch&agrave;o t&acirc;n sinh vi&ecirc;n Khoa Du lịch',
    overview: {
      name: 'Đ&ecirc;m hội Khoa Du lịch',
      client: 'Khoa Du lịch &mdash; HVNN Việt Nam',
      place: 'Học viện Nông nghiệp Việt Nam',
      time: 'Theo lịch khoa',
      scale: 'Sự kiện s&acirc;n trường',
      services: 'S&acirc;n khấu, &acirc;m thanh, &aacute;nh s&aacute;ng, MC',
    },
    intros: [
      { h: 'Ý tưởng', p: 'Kh&ocirc;ng gian gần gũi, nhấn mạnh ng&agrave;nh Du lịch với backdrop v&agrave; phần mở m&agrave;n tương t&aacute;c.' },
      { h: 'Triển khai', p: 'D&agrave;n &acirc;m line array vừa phủ s&acirc;n, đ&egrave;n wash ấm cho buổi tối ngo&agrave;i trời/ hội trường.' },
      { h: 'Kết quả', p: 'T&acirc;n sinh vi&ecirc;n tham gia game, giao lưu ổn định trong khung giờ.' },
    ],
    quote: 'Chương tr&igrave;nh đ&uacute;ng tinh thần khoa, MC v&agrave; &acirc;m thanh ổn.',
    cite: 'Đại diện khoa',
    results: ['Đ&uacute;ng tiến độ', 'Kh&ocirc;ng cố điện', 'Phản hồi t&iacute;ch cực từ t&acirc;n K'],
    experienceBullets: ['Kh&aacute;n giả gần s&acirc;n khấu', 'Kh&ocirc;ng kh&iacute; đo&agrave;n kết khoa'],
    feedback: 'Khoa đồng h&agrave;nh suốt buổi, sinh vi&ecirc;n vui v&agrave; gắn kết.',
    related: ['dem-hoi-chao-tan-sinh-vien-khoa-kinh-te.html', 'dem-hoi-chao-tan-sinh-vien-k69.html', 'le-ky-niem-ngay-nha-giao-viet-nam.html'],
  }),

  P({
    file: 'dem-hoi-chao-tan-sinh-vien-khoa-kinh-te.html',
    pool: 'concert',
    titlePlain: 'Đêm hội chào tân sinh viên Khoa Kinh tế — HVNN | FT GROUP E&E',
    descPlain: 'Chào tân Khoa Kinh tế tại Học viện Nông nghiệp Việt Nam — FT GROUP E&E tổ chức sân khấu & âm thanh.',
    keywords: 'chào tân sinh viên, Khoa Kinh tế, HVNN, FT GROUP E&E',
    filters: ['chao-tan-sinh-vien'],
    cardTitle: 'Chào TSV Khoa Kinh tế',
    cardCat: 'Chào tân sinh viên',
    cardDesc: 'Đêm hội tại HVNN — sân khấu và ánh sáng đồng bộ.',
    cat: 'Chào tân sinh viên',
    loc: 'Học viện Nông nghiệp Việt Nam',
    h1: 'Đ&ecirc;m hội ch&agrave;o t&acirc;n sinh vi&ecirc;n Khoa Kinh tế',
    overview: {
      name: 'Đ&ecirc;m hội Khoa Kinh tế',
      client: 'Khoa Kinh tế &mdash; HVNN Việt Nam',
      place: 'Học viện Nông nghiệp Việt Nam',
      time: 'Theo lịch khoa',
      scale: 'Sự kiện s&acirc;n trường',
      services: 'S&acirc;n khấu, &acirc;m thanh, &aacute;nh s&aacute;ng, vận h&agrave;nh',
    },
    intros: [
      { h: 'Mục ti&ecirc;u', p: 'Ch&agrave;o mừng t&acirc;n sinh vi&ecirc;n khối Kinh tế với kh&ocirc;ng kh&iacute; trẻ trung.' },
      { h: 'Giải ph&aacute;p', p: 'Bố cục s&acirc;n khấu r&otilde; luồng di chuyển; thiết kế &aacute;nh s&aacute;ng ph&ugrave; hợp buổi tối.' },
      { h: 'Tổng kết', p: 'Chương tr&igrave;nh đồng bộ MC, game ngắn, tiết mục văn nghệ.' },
    ],
    quote: 'Chương tr&igrave;nh gọn, đ&uacute;ng giờ v&agrave; vui.',
    cite: 'Ban c&aacute;n sự lớp',
    results: ['Vận h&agrave;nh su&ocirc;n sẻ', 'Sinh vi&ecirc;n tham gia đ&ocirc;ng', 'Kỹ thuật ổn định'],
    experienceBullets: ['Kh&ocirc;ng gian khoa ri&ecirc;ng, dễ tương t&aacute;c'],
    feedback: 'Phối hợp tốt với đại diện khoa v&agrave; Đo&agrave;n.',
    related: ['dem-hoi-chao-tan-sinh-vien-khoa-du-lich.html', 'dem-hoi-chao-tan-sinh-vien-k69.html', 'ngay-hoi-chung-toi-la-chien-si.html'],
  }),

  P({
    file: 'dem-hoi-happy-christmas.html',
    pool: 'christmas',
    titlePlain: 'Đêm hội Happy Christmas — Cao đẳng Du lịch và Thương mại Hà Nội | FT GROUP E&E',
    descPlain: 'Sự kiện Noel học đường — trang trí đỏ xanh, ánh sáng festive, không khí Giáng sinh.',
    keywords: 'Noel trường học, Christmas event, Cao đẳng Du lịch Thương mại Hà Nội, FT GROUP E&E',
    filters: ['su-kien-truong-hoc'],
    cardTitle: 'Đêm hội Happy Christmas',
    cardCat: 'Sự kiện trường học · Noel',
    cardDesc: 'Không khí lễ hội đỏ—xanh, đèn và decor cinematic.',
    cat: 'Sự kiện trường học / Noel',
    loc: 'Trường Cao đẳng Du lịch và Thương mại Hà Nội',
    h1: 'Đ&ecirc;m hội &ldquo;Happy Christmas&rdquo;',
    overview: {
      name: 'Happy Christmas',
      client: 'Trường Cao đẳng Du lịch v&agrave; Thương mại H&agrave; Nội',
      place: 'Cơ sở trường (theo kế hoạch BTC)',
      time: 'M&ugrave;a Gi&aacute;ng sinh',
      scale: 'Đ&ecirc;m hội học đường',
      services: 'Trang tr&iacute; theme Noel, &aacute;nh s&aacute;ng, s&acirc;n khấu, &acirc;m thanh',
    },
    intros: [
      { h: 'Kh&ocirc;ng kh&iacute;', p: 'T&ocirc; điểm đỏ &mdash; xanh, đ&egrave;n LED v&agrave; decor để kh&ocirc;ng gian ấm v&agrave; lễ hội.' },
      { h: 'Chiếu s&aacute;ng', p: 'Wash v&agrave; đ&egrave;n phụ trợ chụp ảnh &mdash; ph&ugrave; hợp backdrop check-in.' },
      { h: 'Vận h&agrave;nh', p: 'Rundown MC, nhạc nền, hiệu ứng nhẹ đ&uacute;ng khung giờ trường.' },
    ],
    quote: 'Kh&ocirc;ng kh&iacute; Noel r&otilde; n&eacute;t &mdash; sinh vi&ecirc;n check-in li&ecirc;n tục.',
    cite: 'BTC trường',
    results: ['Decor &aacute;nh s&aacute;ng đồng bộ', 'Kh&ocirc;ng gian ảnh đẹp', 'An to&agrave;n điện'],
    experienceBullets: ['Backdrop chụp h&igrave;nh đ&ocirc;ng đảo', 'Nhạc v&agrave; đ&egrave;n đ&uacute;ng mood Gi&aacute;ng sinh'],
    feedback: 'Trường h&agrave;i l&ograve;ng phần trang tr&iacute; v&agrave; timeline.',
    related: ['dai-nhac-hoi-chao-tan-sinh-vien-cdltk.html', 'ngay-hoi-le-hoi-nuoc.html', 'dem-hoi-chao-tan-sinh-vien-k69.html'],
  }),

  P({
    file: 'dem-nhac-gieo-yeu-thuong.html',
    pool: 'charity',
    titlePlain: 'Đêm nhạc Gieo yêu thương — thiện nguyện | FT GROUP E&E',
    descPlain: 'Đêm nhạc thiện nguyện — hơn 1000 khách; EDISO Ecopark; đấu giá tranh; góp xây điểm trường Lai Châu.',
    keywords: 'đêm nhạc thiện nguyện, Ecopark, FT GROUP E&E, từ thiện',
    filters: ['dai-nhac-hoi', 'su-kien-truong-hoc'],
    cardTitle: 'Đêm nhạc Gieo yêu thương',
    cardCat: 'Đại nhạc hội · Thiện nguyện',
    cardDesc: '1000+ khách — đấu giá tranh, cảm xúc và sân khấu ý nghĩa.',
    cat: 'Đại nhạc hội / Thiện nguyện',
    loc: 'Trường EDISO Ecopark',
    h1: 'Đ&ecirc;m nhạc &ldquo;Gieo y&ecirc;u thương&rdquo;',
    overview: {
      name: 'Gieo y&ecirc;u thương',
      client: 'Trường EDISO Ecopark &amp; đối t&aacute;c BTC',
      place: 'Trường EDISO Ecopark',
      time: 'Theo m&ugrave;a sự kiện',
      scale: 'Hơn 1000 kh&aacute;ch tham dự',
      services: 'S&acirc;n khấu lớn, &acirc;m thanh, beam, vận h&agrave;nh đ&ecirc;m nhạc, media',
    },
    intros: [
      { h: 'Tầm nh&igrave;n', p: 'Lan tỏa y&ecirc;u thương qua &acirc;m nhạc &mdash; đấu gi&aacute; tranh từ thiện, x&acirc;y điểm trường Lao Lử Đề, Lai Ch&acirc;u.' },
      { h: 'Kỹ thuật', p: 'S&acirc;n khấu đủ sức chứa đ&aacute;m đ&ocirc;ng; &acirc;m thanh phủ đều kh&aacute;n đ&agrave;i.' },
      { h: 'Cảm x&uacute;c', p: 'Thiết kế &aacute;nh s&aacute;ng ấm, nhấn khoảnh khắc tri &acirc;n v&agrave; phần đấu gi&aacute;.' },
    ],
    quote: 'Đ&ecirc;m nhạc chạm đến cảm x&uacute;c &mdash; MC v&agrave; &aacute;nh s&aacute;ng đồng h&agrave;nh c&ugrave;ng th&ocirc;ng điệp.',
    cite: 'Đại diện BTC',
    results: ['1000+ lượt tham dự', 'Ấn tượng s&acirc;n khấu', 'Th&ocirc;ng điệp nh&acirc;n văn r&otilde;'],
    experienceBullets: ['Kh&aacute;n đ&agrave;i đồng thanh ca', 'Kh&ocirc;ng kh&iacute; x&uacute;c động khi đấu gi&aacute;'],
    experienceQuote: 'Lan tỏa được từ s&acirc;n khấu đến kh&aacute;n ph&ograve;ng.',
    feedback: 'Đối t&aacute;c đ&aacute;nh gi&aacute; cao phần vận h&agrave;nh &ecirc;m, an to&agrave;n.',
    related: ['dai-nhac-hoi-chao-tan-sinh-vien-cdltk.html', 'dem-hoi-chao-tan-sinh-vien-k69.html', 'le-ky-niem-ngay-nha-giao-viet-nam.html'],
  }),

  P({
    file: 'dai-nhac-hoi-chao-tan-sinh-vien-cdltk.html',
    pool: 'concert',
    titlePlain: 'Đại nhạc hội chào tân sinh viên — CDLTK Hà Nội | FT GROUP E&E',
    descPlain: 'Đại nhạc hội tại Trường Cao đẳng Du lịch và Thương mại Hà Nội. Khách mời: Anh Thơ, Quân AP.',
    keywords: 'đại nhạc hội, Anh Thơ, Quân AP, Cao đẳng Du lịch Thương mại, FT GROUP E&E',
    filters: ['dai-nhac-hoi'],
    cardTitle: 'Đại nhạc hội chào TSV',
    cardCat: 'Đại nhạc hội',
    cardDesc: 'Anh Thơ & Quân AP — đêm nhạc bùng nổ tại CDLTK.',
    cat: 'Đại nhạc hội',
    loc: 'Trường Cao đẳng Du lịch và Thương mại Hà Nội',
    h1: 'Đại nhạc hội ch&agrave;o t&acirc;n sinh vi&ecirc;n',
    overview: {
      name: 'Đại nhạc hội ch&agrave;o TSV',
      client: 'Trường CDLTK H&agrave; Nội',
      place: 'Trường Cao đẳng Du lịch v&agrave; Thương mại H&agrave; Nội',
      time: 'Theo lịch nh&agrave; trường',
      scale: 'Đại nhạc hội ngo&agrave;i trời / s&acirc;n',
      services: 'S&acirc;n khấu, line array, beam, crew kỹ thuật, điều phối nghệ sĩ',
    },
    intros: [
      { h: 'Line-up', p: 'Kh&aacute;ch mời: Anh Thơ, Qu&acirc;n AP &mdash; kết hợp d&ograve;ng nhạc đa thế hệ.' },
      { h: 'S&acirc;n khấu', p: 'Thiết kế d&agrave;n đ&egrave;n beam, wash v&agrave; haze c&oacute; kiểm so&aacute;t cho g&oacute;c quay v&agrave; ảnh.' },
      { h: 'Kỹ thuật', p: 'Monitor nghệ sĩ, backup m&aacute;y ph&aacute;t, checklist an to&agrave;n lưới điện.' },
    ],
    quote: 'Kh&aacute;n giả đứng l&ecirc;n theo từng b&agrave;i hit &mdash; chất show cao.',
    cite: 'Đại diện BTC trường',
    results: ['Show chạy đ&uacute;ng rundown', 'Chất lượng &acirc;m h&igrave;nh ổn', 'Nghệ sĩ h&agrave;i l&ograve;ng monitor'],
    experienceBullets: ['Fan cồng vỗ tay theo nhịp', '&Aacute;nh s&aacute;ng biến h&oacute;a theo từng ca'],
    feedback: 'Nh&agrave; trường v&agrave; sinh vi&ecirc;n đ&aacute;nh gi&aacute; 5 sao phần kỹ thuật.',
    related: ['dem-hoi-happy-christmas.html', 'dem-hoi-chao-tan-sinh-vien-k70.html', 'dem-nhac-gieo-yeu-thuong.html'],
  }),

  P({
    file: 'dem-hoi-chao-tan-sinh-vien-k70.html',
    pool: 'concert',
    titlePlain: 'Đêm hội chào tân sinh viên K70 — Hoàng Tôn, Mason, DJ Jim | FT GROUP E&E',
    descPlain: 'Đại nhạc hội K70: Hoàng Tôn, Rapper Mason Nguyễn, MC Hype Minami, DJ Jim — không khí bùng nổ.',
    keywords: 'K70, Hoàng Tôn, Mason Nguyễn, MC Minami, DJ Jim, FT GROUP E&E',
    filters: ['dai-nhac-hoi', 'chao-tan-sinh-vien'],
    cardTitle: 'Chào TSV K70',
    cardCat: 'Đại nhạc hội · Chào tân',
    cardDesc: 'DJ + rap + hype MC — đêm bùng nổ.',
    cat: 'Đại nhạc hội / Chào tân sinh viên',
    loc: 'Học viện Nông nghiệp Việt Nam',
    h1: 'Đ&ecirc;m hội ch&agrave;o t&acirc;n sinh vi&ecirc;n K70',
    overview: {
      name: 'Ch&agrave;o TSV K70',
      client: 'HVNN Việt Nam',
      place: 'Học viện Nông nghiệp Việt Nam',
      time: 'Lịch Đo&agrave;n &mdash; Hội',
      scale: 'Đại nhạc hội s&acirc;n trường',
      services: 'S&acirc;n khấu concert, DJ booth, sub, beam, crew &acirc;m thanh',
    },
    intros: [
      { h: 'Line-up', p: 'Ho&agrave;ng T&ocirc;n, Mason Nguyễn, MC Hype Minami, DJ Jim.' },
      { h: 'Kh&ocirc;ng kh&iacute;', p: 'Hype li&ecirc;n tục &mdash; ánh s&aacute;ng pulse, laser/smoke theo quy định địa điểm.' },
      { h: 'Vận h&agrave;nh', p: 'Phối hợp DJ &amp; ban nhạc, cue đ&egrave;n ch&iacute;nh x&aacute;c.' },
    ],
    quote: 'S&acirc;n nổ tung &mdash; bass đủ mạnh m&agrave; vẫn kiểm so&aacute;t được.',
    cite: 'Phản hồi sau show',
    results: ['Ổn định suốt set DJ', 'Rap &amp; vocal balance', 'Kh&aacute;n đ&agrave;i an to&agrave;n'],
    experienceBullets: ['Mosh pit tinh thần &mdash; kh&ocirc;ng kh&iacute; festival', 'MC k&eacute;o tương t&aacute;c li&ecirc;n tục'],
    feedback: 'BTC v&agrave; nghệ sĩ khen crew kỹ thuật.',
    related: ['dem-hoi-chao-tan-sinh-vien-k69.html', 'dai-nhac-hoi-chao-tan-sinh-vien-cdltk.html', 'dem-hoi-chao-tan-sinh-vien-khoa-du-lich.html'],
  }),

  P({
    file: 'le-ky-niem-ngay-nha-giao-viet-nam.html',
    pool: 'school',
    titlePlain: 'Lễ kỉ niệm Ngày Nhà giáo Việt Nam — Khoa Chăn nuôi HVNN | FT GROUP E&E',
    descPlain: 'Sự kiện trường học tri ân thầy cô tại Khoa Chăn nuôi, Học viện Nông nghiệp Việt Nam.',
    keywords: '20/11, nhà giáo Việt Nam, HVNN, FT GROUP E&E',
    filters: ['su-kien-truong-hoc'],
    cardTitle: 'Lễ 20/11 Khoa Chăn nuôi',
    cardCat: 'Sự kiện trường học · Lễ kỷ niệm',
    cardDesc: 'Tri ân thầy cô — trang trọng và cảm động.',
    cat: 'Lễ kỷ niệm / Sự kiện trường học',
    loc: 'Khoa Chăn nuôi — Học viện Nông nghiệp Việt Nam',
    h1: 'Lễ kỉ niệm Ng&agrave;y Nh&agrave; gi&aacute;o Việt Nam',
    overview: {
      name: 'Ng&agrave;y Nh&agrave; gi&aacute;o tại Khoa Chăn nu&ocirc;i',
      client: 'Khoa Chăn nu&ocirc;i &mdash; HVNN',
      place: 'Học viện Nông nghiệp Việt Nam',
      time: '20/11 (theo năm)',
      scale: 'Buổi lễ &mdash; văn nghệ',
      services: 'S&acirc;n khấu, &acirc;m thanh hội trường, đ&egrave;n, backdrop',
    },
    intros: [
      { h: 'Kh&ocirc;ng kh&iacute;', p: 'T&ocirc;n vinh nh&agrave; gi&aacute;o với phần lễ trang trọng v&agrave; tiết mục tri &acirc;n.' },
      { h: 'Dựng chương tr&igrave;nh', p: 'Timeline gọn, mic d&agrave;n cho diễn giả v&agrave; m&uacute;a h&aacute;t.' },
      { h: 'Hậu kỳ', p: 'Thu dọn nhanh, b&agrave;n giao mặt bằng sạch.' },
    ],
    quote: 'Kh&ocirc;ng kh&iacute; x&uacute;c động v&agrave; trang trọng.',
    cite: 'Ban gi&aacute;m hiệu khoa',
    results: ['Đ&uacute;ng nghi thức', '&Acirc;m thanh r&otilde; lời ph&aacute;t biểu', 'Kh&ocirc;ng gian ấm'],
    experienceBullets: ['Sinh vi&ecirc;n tặng hoa, vỗ tay', 'Kh&ocirc;ng kh&iacute; tri &acirc;n'],
    feedback: 'Thầy c&ocirc; đ&aacute;nh gi&aacute; cao phần &acirc;m thanh v&agrave; ánh s&aacute;ng.',
    related: ['ngay-hoi-chung-toi-la-chien-si.html', 'dem-hoi-chao-tan-sinh-vien-khoa-du-lich.html', 'dem-hoi-happy-christmas.html'],
  }),

  P({
    file: 'chuong-trinh-khai-truong-tong-hop.html',
    pool: 'opening',
    titlePlain: 'Các chương trình khai trương — doanh nghiệp, trường học, bệnh viện | FT GROUP E&E',
    descPlain: 'Tổng hợp dự án khai trương: ribbon cutting, balloon, lion dance, sân khấu — FT GROUP E&E.',
    keywords: 'khai trương, ribbon cutting, múa lân, FT GROUP E&E',
    filters: ['khai-truong'],
    cardTitle: 'Khai trương tổng hợp',
    cardCat: 'Khai trương',
    cardDesc: 'Doanh nghiệp, trường, bệnh viện — sân khấu & lễ cắt băng.',
    cat: 'Khai trương',
    loc: 'Miền Bắc (theo từng dự án)',
    h1: 'C&aacute;c chương tr&igrave;nh khai trương',
    overview: {
      name: 'Khai trương đa ng&agrave;nh',
      client: 'Doanh nghiệp / Trường học / Bệnh viện (theo hợp đồng)',
      place: 'Theo địa điểm từng dự &aacute;n',
      time: 'Lịch ri&ecirc;ng',
      scale: 'Từ lễ nhỏ đến khai trương quy m&ocirc;',
      services: 'Ribbon, balloon garland, m&uacute;a l&acirc;n, s&acirc;n khấu, backdrop, MC',
    },
    intros: [
      { h: 'Phong c&aacute;ch', p: 'Backdrop sang, cổng ch&agrave;o, điểm chụp ribbon cutting r&otilde; key visual.' },
      { h: 'Nghi thức', p: 'T&ocirc;n trọng timeline cắt băng, đ&oacute;n kh&aacute;ch VIP, chụp b&aacute;o ch&iacute;.' },
      { h: 'Kỹ thuật', p: '&Acirc;m thanh r&otilde; lời ph&aacute;t biểu; ánh s&aacute;ng ph&ugrave; hợp chụp ảnh.' },
    ],
    quote: 'Khai trương đ&uacute;ng &ldquo;ph&uacute;t v&agrave;ng&rdquo; v&agrave; h&igrave;nh ảnh đẹp.',
    cite: 'Kh&aacute;ch h&agrave;ng doanh nghiệp',
    results: ['Nhiều dự &aacute;n repeat', 'Full package trọn g&oacute;i', 'Tư vấn concept theo ng&agrave;nh'],
    experienceBullets: ['Kh&aacute;ch check-in xếp h&agrave;ng cổng decor', 'Lễ cắt băng gọn trong slot'],
    feedback: 'Đối t&aacute;c khen phần MC, trang tr&iacute; v&agrave; kỹ thuật.',
    related: ['thiet-bi-su-kien-showcase.html', 'teambuilding-vietinbank-bac-giang.html', 'dai-nhac-hoi-chao-tan-sinh-vien-cdltk.html'],
  }),

  P({
    file: 'ngay-hoi-trai-nghiem-chien-si-nhi.html',
    pool: 'preschool',
    titlePlain: 'Ngày hội trải nghiệm Chiến sĩ nhí — mầm non | FT GROUP E&E',
    descPlain: 'Ngày hội trải nghiệm an toàn — hoạt động vui chơi có chủ đề cho mầm non.',
    keywords: 'ngày hội trải nghiệm, mầm non, FT GROUP E&E',
    filters: ['trai-nghiem-giao-duc'],
    cardTitle: 'Chiến sĩ nhí',
    cardCat: 'Ngày hội trải nghiệm · Mầm non',
    cardDesc: 'Trò chơi nhẹ, an toàn — không gian màu sắc.',
    cat: 'Ngày hội trải nghiệm / Mầm non',
    loc: 'Theo lịch trường mầm non (miền Bắc)',
    h1: 'Ng&agrave;y hội trải nghiệm &ldquo;Chiến sĩ nh&iacute;&rdquo;',
    overview: {
      name: 'Chiến sĩ nh&iacute;',
      client: 'Trường hợp t&aacute;c mầm non',
      place: 'S&acirc;n trường / hội trường',
      time: 'Ni&ecirc;n học',
      scale: 'Học sinh + phụ huynh',
      services: 'Kịch bản game, &acirc;m thanh vừa phải, đạo cụ, nh&acirc;n sự hiện trường',
    },
    intros: [
      { h: 'Mục ti&ecirc;u', p: 'R&egrave;n th&oacute;i quen qua tr&ograve; chơi &mdash; kh&ocirc;ng gay cấn, ph&ugrave; hợp lứa tuổi.' },
      { h: 'An to&agrave;n', p: 'Check kỹ vật liệu, luồng di chuyển, micro tần ph&ugrave; hợp.' },
      { h: 'Kh&ocirc;ng kh&iacute;', p: 'M&agrave;u sắc, nhạc vui, hướng dẫn vi&ecirc;n gần gũi.' },
    ],
    quote: 'C&aacute;c con vui hết m&igrave;nh, phụ huynh y&ecirc;n t&acirc;m.',
    cite: 'Gi&aacute;o vi&ecirc;n chủ nhiệm',
    results: ['Kh&ocirc;ng tai nạn nhỏ', 'Tham gia t&iacute;ch cực', 'Feedback tốt'],
    experienceBullets: ['Phụ huynh chụp ảnh check-in', 'Trẻ tham gia đồng loạt'],
    feedback: 'Trường book lại năm sau.',
    related: ['ngay-hoi-cung-con-kham-pha.html', 'chuong-trinh-cuoc-dua-ki-thu.html', 'chuong-trinh-le-hoi-nuoc-2.html'],
  }),

  P({
    file: 'ngay-hoi-chung-toi-la-chien-si.html',
    pool: 'school',
    titlePlain: 'Ngày hội Chúng tôi là chiến sĩ — THCS | FT GROUP E&E',
    descPlain: 'Ngày hội trải nghiệm cấp THCS — gắn kết, kỷ luật nhẹ, hoạt động tập thể.',
    keywords: 'THCS, ngày hội trường, FT GROUP E&E',
    filters: ['trai-nghiem-giao-duc', 'su-kien-truong-hoc'],
    cardTitle: 'Chúng tôi là chiến sĩ',
    cardCat: 'Ngày hội trải nghiệm · THCS',
    cardDesc: 'Đồng đội & tinh thần — sân chơi an toàn.',
    cat: 'Ngày hội trải nghiệm / THCS',
    loc: 'Trường THCS (theo chương trình)',
    h1: 'Ng&agrave;y hội &ldquo;Chúng t&ocirc;i l&agrave; chiến sĩ&rdquo;',
    overview: {
      name: 'Chiến sĩ THCS',
      client: 'Trường THCS đối t&aacute;c',
      place: 'S&acirc;n trường',
      time: 'Học kỳ',
      scale: 'Khối THCS',
      services: 'MC, game station, &acirc;m thanh s&acirc;n, cổng ch&agrave;o',
    },
    intros: [
      { h: 'Concept', p: 'Tăng gắn kết lớp &mdash; luật chơi r&otilde;, kh&ocirc;ng đụng chạm thể lực qu&aacute; mức.' },
      { h: 'Tổ chức', p: 'Chia đội, bảng điểm, nhạc nền động.' },
      { h: 'Hậu kỳ', p: 'Tổng kết nhanh, trao giải phong tr&agrave;o.' },
    ],
    quote: 'C&aacute;c em h&aacute;o hức tham gia từng trạm.',
    cite: 'Tổng phụ tr&aacute;ch Đội',
    results: ['Kỷ luật tốt', 'Vui', 'Kh&ocirc;ng sự cố'],
    experienceBullets: ['Đồng phục đội r&otilde; m&agrave;u', 'Kh&aacute;n đ&agrave;i cổ vũ'],
    feedback: 'Nh&agrave; trường muốn giữ format cho năm sau.',
    related: ['ngay-hoi-trai-nghiem-chien-si-nhi.html', 'chuyen-de-phong-chay-chua-chay.html', 'le-ky-niem-ngay-nha-giao-viet-nam.html'],
  }),

  P({
    file: 'ngay-hoi-le-hoi-nuoc.html',
    pool: 'waterplay',
    titlePlain: 'Ngày hội Lễ hội nước — mầm non | FT GROUP E&E',
    descPlain: 'Chương trình lễ hội nước an toàn cho mầm non — FT GROUP E&E đồng hành thiết bị & nhân sự.',
    keywords: 'lễ hội nước, mầm non, FT GROUP E&E',
    filters: ['trai-nghiem-giao-duc'],
    cardTitle: 'Lễ hội nước',
    cardCat: 'Ngày hội trải nghiệm · Mầm non',
    cardDesc: 'Splash party có kiểm soát — vui và mát.',
    cat: 'Ngày hội trải nghiệm / Mầm non',
    loc: 'Theo sân trường (miền Bắc)',
    h1: 'Ng&agrave;y hội &ldquo;Lễ hội nước&rdquo;',
    overview: {
      name: 'Lễ hội nước (bản 1)',
      client: 'Trường mầm non',
      place: 'S&acirc;n trường',
      time: 'M&ugrave;a h&egrave;',
      scale: 'Học sinh + PH',
      services: 'Khu vực nước, m&aacute;y bơm, nh&acirc;n sự giữ an to&agrave;n, nhạc',
    },
    intros: [
      { h: 'An to&agrave;n', p: 'SOP nước, chống trơn, ph&acirc;n luồng v&agrave;o/ra.' },
      { h: 'Vui', p: 'Tr&ograve; nhẹ, m&agrave;u sắc, MC dẫn nhịp.' },
      { h: 'Kỹ thuật', p: 'Che m&aacute;y, c&aacute;p điện xa khu ướt.' },
    ],
    quote: 'Trẻ cười suốt buổi &mdash; phụ huynh đứng ngo&agrave;i vẫn thấy r&otilde; luồng.',
    cite: 'Ban gi&aacute;m hiệu',
    results: ['Kh&ocirc;ng sự cố', 'Phản hồi tốt', 'Lặp lại hằng năm'],
    experienceBullets: ['Ảnh kỉ niệm ướt &aacute;o đồng phục', 'Bé th&iacute;ch trạm phun nước'],
    feedback: 'Đội hiện trường chuy&ecirc;n nghiệp.',
    related: ['chuong-trinh-le-hoi-nuoc-2.html', 'ngay-hoi-trai-nghiem-chien-si-nhi.html', 'ngay-hoi-cung-con-kham-pha.html'],
  }),

  P({
    file: 'ngay-hoi-cung-con-kham-pha.html',
    pool: 'preschool',
    titlePlain: 'Ngày hội Cùng con khám phá — mầm non | FT GROUP E&E',
    descPlain: 'Ngày hội khám phá cùng phụ huynh — trạm trải nghiệm, decor thân thiện.',
    keywords: 'mầm non, ngày hội gia đình, FT GROUP E&E',
    filters: ['trai-nghiem-giao-duc'],
    cardTitle: 'Cùng con khám phá',
    cardCat: 'Ngày hội trải nghiệm · Mầm non',
    cardDesc: 'Phụ huynh đồng hành — trạm học chơi.',
    cat: 'Ngày hội trải nghiệm / Mầm non',
    loc: 'Trường / đối tác FT',
    h1: 'Ng&agrave;y hội &ldquo;C&ugrave;ng con kh&aacute;m ph&aacute;&rdquo;',
    overview: {
      name: 'C&ugrave;ng con kh&aacute;m ph&aacute;',
      client: 'Trường MN',
      place: 'S&acirc;n trường',
      time: 'Theo lịch',
      scale: 'PH + học sinh',
      services: 'Booth trạm, nhạc, hướng dẫn, decor',
    },
    intros: [
      { h: 'Ý tưởng', p: 'Mỗi trạm một chủ đề khoa học nhẹ nh&agrave;ng.' },
      { h: 'Trải nghiệm', p: 'Phụ huynh l&agrave;m c&ugrave;ng con &mdash; tăng gắn kết.' },
      { h: 'Setup', p: 'B&agrave;n ghế thấp, an to&agrave;n g&oacute;c cạnh.' },
    ],
    quote: 'Gia đ&igrave;nh tham gia nhiệt t&igrave;nh.',
    cite: 'BTC',
    results: ['Tương t&aacute;c cao', 'Ảnh đẹp', 'Thu dọn nhanh'],
    experienceBullets: ['Trạm chơi có hướng dẫn', 'Check-in gia đ&igrave;nh'],
    feedback: 'Trường tiếp tục tin tưởng FT.',
    related: ['ngay-hoi-trai-nghiem-chien-si-nhi.html', 'chuong-trinh-cuoc-dua-ki-thu.html', 'ngay-hoi-le-hoi-nuoc.html'],
  }),

  P({
    file: 'chuyen-de-phong-chay-chua-chay.html',
    pool: 'elementary',
    titlePlain: 'Chuyên đề phòng cháy chữa cháy — tiểu học | FT GROUP E&E',
    descPlain: 'Chuyên đề an toàn PCCC cho tiểu học — mô hình, hướng dẫn, minh họa.',
    keywords: 'PCCC trường học, tiểu học, FT GROUP E&E',
    filters: ['trai-nghiem-giao-duc'],
    cardTitle: 'Chuyên đề PCCC',
    cardCat: 'Ngày hội trải nghiệm · Tiểu học',
    cardDesc: 'Kiến thức an toàn qua hoạt động.',
    cat: 'Ngày hội trải nghiệm / Tiểu học',
    loc: 'Trường tiểu học (miền Bắc)',
    h1: 'Chuy&ecirc;n đề &ldquo;Ph&ograve;ng ch&aacute;y chữa ch&aacute;y&rdquo;',
    overview: {
      name: 'PCCC tiểu học',
      client: 'Trường tiểu học',
      place: 'Hội trường / s&acirc;n',
      time: 'Theo lịch',
      scale: 'Cả khối',
      services: 'Kịch bản, &acirc;m thanh, m&ocirc; h&igrave;nh minh họa, MC',
    },
    intros: [
      { h: 'Gi&aacute;o dục', p: 'Ng&ocirc;n ngữ ph&ugrave; hợp lứa tuổi &mdash; nhấn tho&aacute;t hiểm, gọi cứu hỏa.' },
      { h: 'Minh họa', p: 'Trạm m&ocirc; phỏng, đường tho&aacute;t hiểm m&ocirc; phỏng.' },
      { h: 'An to&agrave;n', p: 'Kh&ocirc;ng d&ugrave;ng lửa thật gần trẻ; video/đạo cụ an to&agrave;n.' },
    ],
    quote: 'HS nhớ quy tr&igrave;nh 4 bước r&otilde; r&agrave;ng.',
    cite: 'Tổ phụ tr&aacute;ch',
    results: ['Tăng nhận thức', 'Đ&aacute;nh gi&aacute; sau khảo s&aacute;t tốt'],
    experienceBullets: ['Thầy c&ocirc; đồng h&agrave;nh từng lớp', 'Hỏi đ&aacute;p cuối buổi'],
    feedback: 'Hiệu trưởng muốn lặp lại mỗi năm.',
    related: ['chuyen-de-gia-dinh-yeu-thuong.html', 'chuyen-de-khoa-hoc-dieu-ki-a.html', 'ngay-hoi-chung-toi-la-chien-si.html'],
  }),

  P({
    file: 'chuyen-de-gia-dinh-yeu-thuong.html',
    pool: 'elementary',
    titlePlain: 'Chuyên đề Gia đình yêu thương — tiểu học | FT GROUP E&E',
    descPlain: 'Chương trình kết nối gia đình — hoạt động cảm xúc, game nhẹ.',
    keywords: 'gia đình yêu thương, tiểu học, FT GROUP E&E',
    filters: ['trai-nghiem-giao-duc'],
    cardTitle: 'Gia đình yêu thương',
    cardCat: 'Ngày hội trải nghiệm · Tiểu học',
    cardDesc: 'Cảm xúc & kết nối PH — học sinh.',
    cat: 'Ngày hội trải nghiệm / Tiểu học',
    loc: 'Trường tiểu học',
    h1: 'Chuy&ecirc;n đề &ldquo;Gia đ&igrave;nh y&ecirc;u thương&rdquo;',
    overview: {
      name: 'Gia đ&igrave;nh y&ecirc;u thương',
      client: 'Trường TH',
      place: 'Hội trường',
      time: 'Ni&ecirc;n học',
      scale: 'HS + PH',
      services: 'Kịch bản cảm x&uacute;c, nhạc, backdrop, tổ chức game',
    },
    intros: [
      { h: 'Mục ti&ecirc;u', p: 'Tăng hiểu biết lẫn nhau trong gia đ&igrave;nh.' },
      { h: 'Hoạt động', p: 'Thư đi, game nh&oacute;m nhỏ, chia sẻ tr&ecirc;n s&acirc;n khấu nhẹ.' },
      { h: 'Kh&ocirc;ng kh&iacute;', p: 'Nhạc ấm, &aacute;nh s&aacute;ng dịu.' },
    ],
    quote: 'Nhiều phụ huynh x&uacute;c động.',
    cite: 'GVCN',
    results: ['Feedback PH t&iacute;ch cực', 'Kh&ocirc;ng qu&aacute; tải thời lượng'],
    experienceBullets: ['PH ôm con l&ecirc;n stage game nhỏ'],
    feedback: 'BTC muốn giữ format cho khối kh&aacute;c.',
    related: ['chuyen-de-phong-chay-chua-chay.html', 'chuyen-de-khoa-hoc-dieu-ki-b.html', 'ngay-hoi-cung-con-kham-pha.html'],
  }),

  P({
    file: 'chuyen-de-khoa-hoc-dieu-ki-a.html',
    pool: 'elementary',
    titlePlain: 'Chuyên đề Khoa học diệu kì — tiểu học (lớp 1) | FT GROUP E&E',
    descPlain: 'Chuyên đề STEM nhẹ — quan sát, thí nghiệm demo an toàn cho tiểu học.',
    keywords: 'khoa học diệu kỳ, STEM, FT GROUP E&E',
    filters: ['trai-nghiem-giao-duc'],
    cardTitle: 'Khoa học diệu kì · A',
    cardCat: 'Ngày hội trải nghiệm · Tiểu học',
    cardDesc: 'Thí nghiệm demo — dễ hiểu, an toàn.',
    cat: 'Ngày hội trải nghiệm / Tiểu học',
    loc: 'Trường tiểu học (lớp ghép A)',
    h1: 'Chuy&ecirc;n đề &ldquo;Khoa học diệu k&igrave;&rdquo; (đợt A)',
    overview: {
      name: 'Khoa học diệu k&igrave; &mdash; đợt A',
      client: 'Trường tiểu học',
      place: 'Ph&ograve;ng học / s&acirc;n',
      time: 'Học kỳ',
      scale: 'Khối lớp',
      services: 'B&agrave;n th&iacute; nghiệm, micro, slide, hướng dẫn',
    },
    intros: [
      { h: 'Nội dung', p: 'Hiện tượng vật l&iacute; đơn giản, quan s&aacute;t m&agrave;u, phản ứng an to&agrave;n.' },
      { h: 'An to&agrave;n', p: 'Ho&aacute; chất food-grade / hoặc chỉ demo video + m&ocirc; h&igrave;nh.' },
      { h: 'Tương t&aacute;c', p: 'HS l&ecirc;n thử trải nghiệm c&oacute; gi&aacute;m s&aacute;t.' },
    ],
    quote: 'Trẻ hỏi li&ecirc;n tục &mdash; tốt cho tư duy.',
    cite: 'Gi&aacute;o vi&ecirc;n Tự nhi&ecirc;n',
    results: ['Tham gia 100%', 'Hiểu kh&aacute;i niệm cơ bản'],
    experienceBullets: ['Bang m&agrave;u chữ A', 'Th&iacute; nghiệm nước trong khay'],
    feedback: 'Phụ huynh khen phần minh họa.',
    related: ['chuyen-de-khoa-hoc-dieu-ki-b.html', 'chuyen-de-phong-chay-chua-chay.html', 'chuong-trinh-cuoc-dua-ki-thu.html'],
  }),

  P({
    file: 'chuyen-de-khoa-hoc-dieu-ki-b.html',
    pool: 'elementary',
    titlePlain: 'Chuyên đề Khoa học diệu kì — tiểu học (lớp 2) | FT GROUP E&E',
    descPlain: 'Phiên bản triển khai thứ hai — nội dung mở rộng theo độ tuổi.',
    keywords: 'khoa học, trải nghiệm, FT GROUP E&E',
    filters: ['trai-nghiem-giao-duc'],
    cardTitle: 'Khoa học diệu kì · B',
    cardCat: 'Ngày hội trải nghiệm · Tiểu học',
    cardDesc: 'Đợt B — nội dung nâng theo lớp.',
    cat: 'Ngày hội trải nghiệm / Tiểu học',
    loc: 'Trường tiểu học (lớp ghép B)',
    h1: 'Chuy&ecirc;n đề &ldquo;Khoa học diệu k&igrave;&rdquo; (đợt B)',
    overview: {
      name: 'Khoa học diệu k&igrave; &mdash; đợt B',
      client: 'C&ugrave;ng hệ thống / khối kh&aacute;c',
      place: 'Trường',
      time: 'Học kỳ',
      scale: 'Khối lớp',
      services: 'Giống đợt A &mdash; t&ugrave;y chỉnh độ kh&oacute; b&agrave;i lab',
    },
    intros: [
      { h: 'Kh&aacute;c biệt', p: 'Th&ecirc;m trạm robot demo / pin mặt trời m&ocirc; phỏng.' },
      { h: 'Kỹ thuật', p: 'C&ugrave;ng SOP an to&agrave;n như đợt A.' },
      { h: 'Kết quả', p: 'HS trả lời c&acirc;u hỏi tương t&aacute;c cuối giờ.' },
    ],
    quote: 'Đợt B giữ được sự tập trung cao.',
    cite: 'BTC',
    results: ['Điểm tương t&aacute;c cuối giờ cao'],
    experienceBullets: ['HS thích trạm robot hơn'],
    feedback: 'Nh&agrave; trường h&agrave;i l&ograve;ng.',
    related: ['chuyen-de-khoa-hoc-dieu-ki-a.html', 'chuyen-de-gia-dinh-yeu-thuong.html', 'chuyen-de-phong-chay-chua-chay.html'],
  }),

  P({
    file: 'chuong-trinh-le-hoi-nuoc-2.html',
    pool: 'waterplay',
    titlePlain: 'Chương trình Lễ hội nước — mầm non | FT GROUP E&E',
    descPlain: 'Phiên triển khai chương trình Lễ hội nước (bản 2) — cùng format an toàn.',
    keywords: 'lễ hội nước, mầm non, FT GROUP E&E',
    filters: ['trai-nghiem-giao-duc'],
    cardTitle: 'Lễ hội nước (chương trình)',
    cardCat: 'Ngày hội trải nghiệm · Mầm non',
    cardDesc: 'Chương trình đã chứng minh — lặp tại trường khác.',
    cat: 'Ngày hội trải nghiệm / Mầm non',
    loc: 'Theo hợp đồng',
    h1: 'Chương tr&igrave;nh &ldquo;Lễ hội nước&rdquo;',
    overview: {
      name: 'Lễ hội nước &mdash; g&oacute;i chương tr&igrave;nh',
      client: 'Trường MN đối t&aacute;c',
      place: 'S&acirc;n trường',
      time: 'M&ugrave;a h&egrave;',
      scale: 'Full khối',
      services: 'Full setup khu nước + crew giữ trật tự',
    },
    intros: [
      { h: 'Scale', p: 'Nhiều trường đ&atilde; triển khai &mdash; checklist chuẩn FT.' },
      { h: 'Sự kh&aacute;c biệt', p: 'T&ugrave;y s&acirc;n m&agrave; bố tr&iacute; lượng v&ograve;i phun.' },
      { h: 'Cam kết', p: 'An to&agrave;n đặt tr&ecirc;n hết.' },
    ],
    quote: 'PH y&ecirc;n t&acirc;m đứng r&agrave;o quan s&aacute;t.',
    cite: 'Hiệu trưởng',
    results: ['0 sự cố', 'Book lại'],
    experienceBullets: ['Cổng check-in nhanh'],
    feedback: 'FT được giới thiệu sang trường bạn.',
    related: ['ngay-hoi-le-hoi-nuoc.html', 'ngay-hoi-trai-nghiem-chien-si-nhi.html', 'ngay-hoi-cung-con-kham-pha.html'],
  }),

  P({
    file: 'chuong-trinh-cuoc-dua-ki-thu.html',
    pool: 'preschool',
    titlePlain: 'Chương trình Cuộc đua kì thú — mầm non | FT GROUP E&E',
    descPlain: 'Trò chơi vận động nhẹ — chủ đề phiêu lưu an toàn cho lứa mầm non.',
    keywords: 'mầm non, trò chơi, FT GROUP E&E',
    filters: ['trai-nghiem-giao-duc'],
    cardTitle: 'Cuộc đua kì thú',
    cardCat: 'Ngày hội trải nghiệm · Mầm non',
    cardDesc: 'Đường đua mềm — mascot dẫn đội.',
    cat: 'Ngày hội trải nghiệm / Mầm non',
    loc: 'Sân trường',
    h1: 'Chương tr&igrave;nh &ldquo;Cuộc đua k&igrave; th&uacute;&rdquo;',
    overview: {
      name: 'Cuộc đua k&igrave; th&uacute;',
      client: 'Trường MN',
      place: 'S&acirc;n',
      time: 'Sự kiện năm học',
      scale: 'Cả trường chia ca',
      services: 'Trạm game, r&agrave;o chắn mềm, nhạc, MC hoạt h&igrave;nh',
    },
    intros: [
      { h: 'An to&agrave;n', p: 'Kh&ocirc;ng cạnh tranh căng; tập thể vui.' },
      { h: 'M&agrave;u sắc', p: 'Backrop chủ đề rừng/đường đua mềm.' },
      { h: 'Vận h&agrave;nh', p: 'Nh&acirc;n sự mỗi trạm giữ luồng.' },
    ],
    quote: 'B&eacute; cười suốt đường đua.',
    cite: 'C&ocirc; gi&aacute;o',
    results: ['Vui', 'An to&agrave;n', 'H&igrave;nh ảnh đẹp'],
    experienceBullets: ['Mascot chụp ảnh c&ugrave;ng b&eacute;'],
    feedback: 'Trường muốn giữ mascot c&ugrave;ng concept.',
    related: ['ngay-hoi-trai-nghiem-chien-si-nhi.html', 'chuong-trinh-le-hoi-nuoc-2.html', 'ngay-hoi-cung-con-kham-pha.html'],
  }),

  P({
    file: 'teambuilding-vietinbank-bac-giang.html',
    pool: 'team',
    titlePlain: 'Teambuilding Vietinbank Bắc Giang | FT GROUP E&E',
    descPlain: 'Outdoor team building — cán bộ CNV Vietinbank Bắc Giang; trò chơi nhóm, gắn kết.',
    keywords: 'teambuilding, Vietinbank, Bắc Giang, FT GROUP E&E',
    filters: ['team-building'],
    cardTitle: 'TB Vietinbank Bắc Giang',
    cardCat: 'Team Building',
    cardDesc: 'Outdoor — game nhóm & bonding công ty.',
    cat: 'Team Building doanh nghiệp',
    loc: 'Bắc Giang',
    h1: 'Teambuilding Vietinbank Bắc Giang',
    overview: {
      name: 'TB Vietinbank BG',
      client: 'Vietinbank chi nh&aacute;nh Bắc Giang',
      place: 'Địa điểm outdoor theo hợp đồng',
      time: 'Theo lịch DN',
      scale: 'C&aacute;n bộ CNV',
      services: 'Facilitator, tr&ograve; chơi, &acirc;m thanh s&acirc;n, s&acirc;n khấu nhỏ',
    },
    intros: [
      { h: 'Mục ti&ecirc;u', p: 'Tăng gắn kết ph&ograve;ng ban sau giờ l&agrave;m.' },
      { h: 'Hoạt động', p: 'Ice-break, chiến thuật nh&oacute;m, tổng kết vui.' },
      { h: 'Logistics', p: 'Sound outdoor, che nắng, nước uống, y tế sơ cấp.' },
    ],
    quote: 'Thắng thua đều vui &mdash; quan trọng l&agrave; đồng đội cười nhiều.',
    cite: 'HR',
    results: ['Engagement cao', 'Kh&ocirc;ng chấn thương', 'Survey nội bộ tốt'],
    experienceBullets: ['Ảnh flycam tập thể', 'Tr&ograve; cười đồng loạt'],
    feedback: 'Phòng nh&acirc;n sự book lại.',
    related: ['teambuilding-nha-khoa-nhu-ngoc.html', 'chuong-trinh-khai-truong-tong-hop.html', 'thiet-bi-su-kien-showcase.html'],
  }),

  P({
    file: 'teambuilding-nha-khoa-nhu-ngoc.html',
    pool: 'team',
    titlePlain: 'Teambuilding Nha khoa Như Ngọc | FT GROUP E&E',
    descPlain: 'Teambuilding nội bộ phòng khám — chuyên nghiệp, gọn, đúng timeline.',
    keywords: 'teambuilding nha khoa, FT GROUP E&E',
    filters: ['team-building'],
    cardTitle: 'TB Nha khoa Như Ngọc',
    cardCat: 'Team Building',
    cardDesc: 'Gắn kết đội ngũ y bác sĩ & hành chính.',
    cat: 'Team Building doanh nghiệp',
    loc: 'Hà Nội / vùng phụ cận',
    h1: 'Teambuilding Nha khoa Như Ngọc',
    overview: {
      name: 'TB Nha khoa Như Ngọc',
      client: 'Ph&ograve;ng kh&aacute;m Nha khoa Như Ngọc',
      place: 'Địa điểm gọn trong ng&agrave;y',
      time: 'Theo lịch',
      scale: 'To&agrave;n bộ nh&acirc;n sự',
      services: 'Facilitator, game nh&oacute;m nhỏ, MC, nhạc nền',
    },
    intros: [
      { h: 'Đặc th&ugrave;', p: 'Khung giờ gắn lịch kh&aacute;m &mdash; setup nhanh.' },
      { h: 'Nội dung', p: 'Game nhẹ không ảnh hưởng tay nghề ng&agrave;y sau.' },
      { h: 'Tinh thần', p: 'Nhấn hợp t&aacute;c giữa lễ t&acirc;n &mdash; b&aacute;c sĩ.' },
    ],
    quote: 'Tập thể gần nhau hơn sau 1 buổi chiều.',
    cite: 'Quản lý ph&ograve;ng kh&aacute;m',
    results: ['Kh&ocirc;ng ảnh hưởng lịch hẹn', 'Team feedback 4.8/5'],
    experienceBullets: ['Chụp ảnh đồng phục đẹp'],
    feedback: 'Giới thiệu cho ph&ograve;ng kh&aacute;m kh&aacute;c.',
    related: ['teambuilding-vietinbank-bac-giang.html', 'chuong-trinh-khai-truong-tong-hop.html', 'thiet-bi-su-kien-showcase.html'],
  }),

  P({
    file: 'thiet-bi-su-kien-showcase.html',
    pool: 'equipment',
    titlePlain: 'Thiết bị sự kiện — âm thanh, ánh sáng, LED | FT GROUP E&E',
    descPlain: 'Tổng hợp năng lực thiết bị: âm thanh, ánh sáng, sân khấu, LED, photobooth, check-in, 3D, giáo cụ, TB, cổng hơi.',
    keywords: 'cho thuê thiết bị sự kiện, LED, FT GROUP E&E',
    filters: ['thiet-bi-su-kien'],
    cardTitle: 'Thiết bị sự kiện',
    cardCat: 'Thiết bị',
    cardDesc: 'Full catalog — lắp đặt & vận hành kỹ thuật.',
    cat: 'Thiết bị sự kiện',
    loc: 'Kho & vận chuyển miền Bắc',
    h1: 'Thiết bị sự kiện &mdash; catalog triển khai',
    overview: {
      name: 'G&oacute;i thiết bị FT',
      client: 'Nhiều đối t&aacute;c / sự kiện',
      place: 'Theo địa điểm job',
      time: '365 ng&agrave;y',
      scale: 'Từ job nhỏ đến festival',
      services: '&Acirc;m thanh, &aacute;nh s&aacute;ng, LED, s&acirc;n khấu, photobooth, check-in, 3D mapping, gi&aacute;o cụ TE, cổng hơi',
    },
    intros: [
      { h: 'Catalog', p: 'Line array, sub, beam, wash, LED indoor/outdoor, truss, m&aacute;y bơm sương, backdrop.' },
      { h: 'Vận h&agrave;nh', p: 'Kỹ thuật vi&ecirc;n onsite, checklist, backup thiết bị.' },
      { h: 'Trải nghiệm', p: 'Đồng bộ creative v&agrave; an to&agrave;n tải điện.' },
    ],
    quote: 'Một đầu mối thiết bị &mdash; giảm rủi ro đối t&aacute;c.',
    cite: 'Quản lý kỹ thuật FT',
    results: ['Bảo tr&igrave; trước job', 'Bi&ecirc;n bản b&agrave;n giao r&otilde;'],
    experienceBullets: ['Kh&aacute;ch xem dry-run trước giờ G'],
    feedback: 'Đối t&aacute;c sản xuất show tin tưởng lineup m&aacute;y.',
    related: ['dai-nhac-hoi-chao-tan-sinh-vien-cdltk.html', 'chuong-trinh-khai-truong-tong-hop.html', 'teambuilding-vietinbank-bac-giang.html'],
  }),
];
